<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Data Structures | R Programming for Data Sciences</title>
  <meta name="description" content="Chapter 4 Data Structures | R Programming for Data Sciences" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Data Structures | R Programming for Data Sciences" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Data Structures | R Programming for Data Sciences" />
  
  
  

<meta name="author" content="Andrew O. Finley, Jeffrey W. Doser, Vince Melfi" />


<meta name="date" content="2021-06-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scripts.html"/>
<link rel="next" href="ggplot2.html"/>
<script src="libs/header-attrs/header-attrs.js"></script>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block/empty-anchor.js"></script>
<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<script src="libs/kePrint/kePrint.js"></script>
<link href="libs/lightable/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets/htmlwidgets.js"></script>
<link href="libs/leaflet/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet/leaflet.js"></script>
<link href="libs/leafletfix/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4/proj4.min.js"></script>
<script src="libs/Proj4Leaflet/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding/leaflet.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Programming for Data Sciences</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Description</a></li>
<li class="chapter" data-level="1" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>1</b> Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data.html"><a href="data.html#baby-crawling-data"><i class="fa fa-check"></i><b>1.1</b> Baby crawling data</a></li>
<li class="chapter" data-level="1.2" data-path="data.html"><a href="data.html#world-bank-data"><i class="fa fa-check"></i><b>1.2</b> World bank data</a></li>
<li class="chapter" data-level="1.3" data-path="data.html"><a href="data.html#email-data"><i class="fa fa-check"></i><b>1.3</b> Email data</a></li>
<li class="chapter" data-level="1.4" data-path="data.html"><a href="data.html#handwritten-digit-recognition"><i class="fa fa-check"></i><b>1.4</b> Handwritten digit recognition</a></li>
<li class="chapter" data-level="1.5" data-path="data.html"><a href="data.html#looking-forward"><i class="fa fa-check"></i><b>1.5</b> Looking forward</a></li>
<li class="chapter" data-level="1.6" data-path="data.html"><a href="data.html#how-to-learn-the-most-important-section-in-this-book"><i class="fa fa-check"></i><b>1.6</b> How to learn (the most important section in this book!)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>2</b> Introduction to R and RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#obtaining-and-installing-r"><i class="fa fa-check"></i><b>2.1</b> Obtaining and installing R</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#obtaining-and-installing-rstudio"><i class="fa fa-check"></i><b>2.2</b> Obtaining and installing RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#using-r-and-rstudio"><i class="fa fa-check"></i><b>2.3</b> Using R and RStudio</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#rstudio-themes"><i class="fa fa-check"></i><b>2.3.1</b> Rstudio themes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#packages"><i class="fa fa-check"></i><b>2.4</b> Installing and calling R packages</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#RCalculator"><i class="fa fa-check"></i><b>2.5</b> R as a calculator</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#RDescriptive"><i class="fa fa-check"></i><b>2.5.1</b> Initial look at vectors and data</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#an-initial-tour-of-rstudio"><i class="fa fa-check"></i><b>2.5.2</b> An Initial Tour of RStudio</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#introRPractice"><i class="fa fa-check"></i><b>2.5.3</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#workingDirectory"><i class="fa fa-check"></i><b>2.6</b> Workspace, working directory, and keeping organized</a></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#getting-help"><i class="fa fa-check"></i><b>2.7</b> Getting Help</a></li>
<li class="chapter" data-level="2.8" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#practiceProblemsSectionIntroR"><i class="fa fa-check"></i><b>2.8</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="scripts.html"><a href="scripts.html"><i class="fa fa-check"></i><b>3</b> Scripts and R Markdown</a>
<ul>
<li class="chapter" data-level="3.1" data-path="scripts.html"><a href="scripts.html#scripts-in-r"><i class="fa fa-check"></i><b>3.1</b> Scripts in R</a></li>
<li class="chapter" data-level="3.2" data-path="scripts.html"><a href="scripts.html#quality-of-r-code"><i class="fa fa-check"></i><b>3.2</b> Quality of R code</a></li>
<li class="chapter" data-level="3.3" data-path="scripts.html"><a href="scripts.html#best-practices-for-naming-and-formatting"><i class="fa fa-check"></i><b>3.3</b> Best practices for naming and formatting</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="scripts.html"><a href="scripts.html#script-file-naming"><i class="fa fa-check"></i><b>3.3.1</b> Script file naming</a></li>
<li class="chapter" data-level="3.3.2" data-path="scripts.html"><a href="scripts.html#variable-naming"><i class="fa fa-check"></i><b>3.3.2</b> Variable naming</a></li>
<li class="chapter" data-level="3.3.3" data-path="scripts.html"><a href="scripts.html#code-formatting"><i class="fa fa-check"></i><b>3.3.3</b> Code formatting</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="scripts.html"><a href="scripts.html#markdown"><i class="fa fa-check"></i><b>3.4</b> R Markdown</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="scripts.html"><a href="scripts.html#creating-and-processing-r-markdown-documents"><i class="fa fa-check"></i><b>3.4.1</b> Creating and processing R Markdown documents</a></li>
<li class="chapter" data-level="3.4.2" data-path="scripts.html"><a href="scripts.html#text-lists-and-headers"><i class="fa fa-check"></i><b>3.4.2</b> Text: Lists and Headers</a></li>
<li class="chapter" data-level="3.4.3" data-path="scripts.html"><a href="scripts.html#chunks"><i class="fa fa-check"></i><b>3.4.3</b> Code Chunks</a></li>
<li class="chapter" data-level="3.4.4" data-path="scripts.html"><a href="scripts.html#output-formats-other-than-html"><i class="fa fa-check"></i><b>3.4.4</b> Output formats other than HTML</a></li>
<li class="chapter" data-level="3.4.5" data-path="scripts.html"><a href="scripts.html#kables"><i class="fa fa-check"></i><b>3.4.5</b> Tables, <code>kable</code>, and <code>kableExtra</code></a></li>
<li class="chapter" data-level="3.4.6" data-path="scripts.html"><a href="scripts.html#latex-knitr-and-bookdown"><i class="fa fa-check"></i><b>3.4.6</b> LaTeX, <code>knitr</code>, and <code>bookdown</code></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="scripts.html"><a href="scripts.html#practiceProblemsRMarkdown"><i class="fa fa-check"></i><b>3.5</b> Practice Problems</a></li>
<li class="chapter" data-level="3.6" data-path="scripts.html"><a href="scripts.html#exCh3"><i class="fa fa-check"></i><b>3.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="structures.html"><a href="structures.html"><i class="fa fa-check"></i><b>4</b> Data Structures</a>
<ul>
<li class="chapter" data-level="4.1" data-path="structures.html"><a href="structures.html#vector"><i class="fa fa-check"></i><b>4.1</b> Vectors</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="structures.html"><a href="structures.html#types-conversion-coercion"><i class="fa fa-check"></i><b>4.1.1</b> Types, Conversion, Coercion</a></li>
<li class="chapter" data-level="4.1.2" data-path="structures.html"><a href="structures.html#accessing-specific-elements-of-vectors"><i class="fa fa-check"></i><b>4.1.2</b> Accessing Specific Elements of Vectors</a></li>
<li class="chapter" data-level="4.1.3" data-path="structures.html"><a href="structures.html#ch4PP1"><i class="fa fa-check"></i><b>4.1.3</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="structures.html"><a href="structures.html#factors"><i class="fa fa-check"></i><b>4.2</b> Factors</a></li>
<li class="chapter" data-level="4.3" data-path="structures.html"><a href="structures.html#missing-data-infinity-etc."><i class="fa fa-check"></i><b>4.3</b> Missing Data, Infinity, etc.</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="structures.html"><a href="structures.html#ch4PP2"><i class="fa fa-check"></i><b>4.3.1</b> Practice Problem</a></li>
<li class="chapter" data-level="4.3.2" data-path="structures.html"><a href="structures.html#infinity-and-nan"><i class="fa fa-check"></i><b>4.3.2</b> Infinity and NaN</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="structures.html"><a href="structures.html#dataFrames"><i class="fa fa-check"></i><b>4.4</b> Data Frames</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="structures.html"><a href="structures.html#accessing-specific-elements-of-data-frames"><i class="fa fa-check"></i><b>4.4.1</b> Accessing Specific Elements of Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="structures.html"><a href="structures.html#lists"><i class="fa fa-check"></i><b>4.5</b> Lists</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="structures.html"><a href="structures.html#accessing-specific-elements-of-lists"><i class="fa fa-check"></i><b>4.5.1</b> Accessing Specific Elements of Lists</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="structures.html"><a href="structures.html#logicalOperators"><i class="fa fa-check"></i><b>4.6</b> Comparison and logical operators</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="structures.html"><a href="structures.html#inOperator"><i class="fa fa-check"></i><b>4.6.1</b> The <code>%in%</code> operator</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="structures.html"><a href="structures.html#subsetting"><i class="fa fa-check"></i><b>4.7</b> Subsetting with Logical Vectors</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="structures.html"><a href="structures.html#modifying-or-creating-objects-via-subsetting"><i class="fa fa-check"></i><b>4.7.1</b> Modifying or Creating Objects via Subsetting</a></li>
<li class="chapter" data-level="4.7.2" data-path="structures.html"><a href="structures.html#logical-subsetting-and-data-frames"><i class="fa fa-check"></i><b>4.7.2</b> Logical Subsetting and Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="structures.html"><a href="structures.html#patterned-data"><i class="fa fa-check"></i><b>4.8</b> Patterned Data</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="structures.html"><a href="structures.html#ch4PP3"><i class="fa fa-check"></i><b>4.8.1</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="structures.html"><a href="structures.html#exChapter4"><i class="fa fa-check"></i><b>4.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ggplot2.html"><a href="ggplot2.html"><i class="fa fa-check"></i><b>5</b> Graphics in R Part 1: <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="5.1" data-path="ggplot2.html"><a href="ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>5.1</b> Scatter Plots</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="ggplot2.html"><a href="ggplot2.html#structure-of-a-typical-ggplot"><i class="fa fa-check"></i><b>5.1.1</b> Structure of a Typical <code>ggplot</code></a></li>
<li class="chapter" data-level="5.1.2" data-path="ggplot2.html"><a href="ggplot2.html#adding-lines-to-a-scatter-plot"><i class="fa fa-check"></i><b>5.1.2</b> Adding lines to a scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="ggplot2.html"><a href="ggplot2.html#labels-axes-text-etc."><i class="fa fa-check"></i><b>5.2</b> Labels, Axes, Text, etc.</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="ggplot2.html"><a href="ggplot2.html#labels"><i class="fa fa-check"></i><b>5.2.1</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ggplot2.html"><a href="ggplot2.html#customizing-axes"><i class="fa fa-check"></i><b>5.3</b> Customizing Axes</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="ggplot2.html"><a href="ggplot2.html#text-point-size-and-color"><i class="fa fa-check"></i><b>5.3.1</b> Text, Point Size, and Color</a></li>
<li class="chapter" data-level="5.3.2" data-path="ggplot2.html"><a href="ggplot2.html#ch5PP1"><i class="fa fa-check"></i><b>5.3.2</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="ggplot2.html"><a href="ggplot2.html#other-types-of-graphics"><i class="fa fa-check"></i><b>5.4</b> Other Types of Graphics</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="ggplot2.html"><a href="ggplot2.html#histograms"><i class="fa fa-check"></i><b>5.4.1</b> Histograms</a></li>
<li class="chapter" data-level="5.4.2" data-path="ggplot2.html"><a href="ggplot2.html#boxplots"><i class="fa fa-check"></i><b>5.4.2</b> Boxplots</a></li>
<li class="chapter" data-level="5.4.3" data-path="ggplot2.html"><a href="ggplot2.html#bar-graphs"><i class="fa fa-check"></i><b>5.4.3</b> Bar Graphs</a></li>
<li class="chapter" data-level="5.4.4" data-path="ggplot2.html"><a href="ggplot2.html#graphs-of-functions"><i class="fa fa-check"></i><b>5.4.4</b> Graphs of Functions</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ggplot2.html"><a href="ggplot2.html#themes"><i class="fa fa-check"></i><b>5.5</b> Themes</a></li>
<li class="chapter" data-level="5.6" data-path="ggplot2.html"><a href="ggplot2.html#saving-graphics"><i class="fa fa-check"></i><b>5.6</b> Saving Graphics</a></li>
<li class="chapter" data-level="5.7" data-path="ggplot2.html"><a href="ggplot2.html#more-resources"><i class="fa fa-check"></i><b>5.7</b> More Resources</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="ggplot2.html"><a href="ggplot2.html#ch5PP2"><i class="fa fa-check"></i><b>5.7.1</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="ggplot2.html"><a href="ggplot2.html#exCh5"><i class="fa fa-check"></i><b>5.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data2.html"><a href="data2.html"><i class="fa fa-check"></i><b>6</b> Working with Data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data2.html"><a href="data2.html#import"><i class="fa fa-check"></i><b>6.1</b> Data import</a></li>
<li class="chapter" data-level="6.2" data-path="data2.html"><a href="data2.html#importing-data-with-missing-observations"><i class="fa fa-check"></i><b>6.2</b> Importing data with missing observations</a></li>
<li class="chapter" data-level="6.3" data-path="data2.html"><a href="data2.html#data-export"><i class="fa fa-check"></i><b>6.3</b> Data export</a></li>
<li class="chapter" data-level="6.4" data-path="data2.html"><a href="data2.html#summarizing-data-frames"><i class="fa fa-check"></i><b>6.4</b> Summarizing Data Frames</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="data2.html"><a href="data2.html#column-and-row-summaries"><i class="fa fa-check"></i><b>6.4.1</b> Column (and Row) Summaries</a></li>
<li class="chapter" data-level="6.4.2" data-path="data2.html"><a href="data2.html#apply"><i class="fa fa-check"></i><b>6.4.2</b> The <code>apply()</code> Function</a></li>
<li class="chapter" data-level="6.4.3" data-path="data2.html"><a href="data2.html#ch6PP1"><i class="fa fa-check"></i><b>6.4.3</b> Practice Problems</a></li>
<li class="chapter" data-level="6.4.4" data-path="data2.html"><a href="data2.html#saving-typing-using-with"><i class="fa fa-check"></i><b>6.4.4</b> Saving Typing Using <code>with()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="data2.html"><a href="data2.html#transforming-a-data-frame"><i class="fa fa-check"></i><b>6.5</b> Transforming a Data Frame</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="data2.html"><a href="data2.html#adding-variables"><i class="fa fa-check"></i><b>6.5.1</b> Adding Variables</a></li>
<li class="chapter" data-level="6.5.2" data-path="data2.html"><a href="data2.html#removing-variables"><i class="fa fa-check"></i><b>6.5.2</b> Removing Variables</a></li>
<li class="chapter" data-level="6.5.3" data-path="data2.html"><a href="data2.html#ch6PP2"><i class="fa fa-check"></i><b>6.5.3</b> Practice Problem</a></li>
<li class="chapter" data-level="6.5.4" data-path="data2.html"><a href="data2.html#transforming-variables"><i class="fa fa-check"></i><b>6.5.4</b> Transforming Variables</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="data2.html"><a href="data2.html#rearranging-variables"><i class="fa fa-check"></i><b>6.6</b> Rearranging Variables</a></li>
<li class="chapter" data-level="6.7" data-path="data2.html"><a href="data2.html#reshaping-data"><i class="fa fa-check"></i><b>6.7</b> Reshaping Data</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="data2.html"><a href="data2.html#tidyr"><i class="fa fa-check"></i><b>6.7.1</b> <code>tidyr</code></a></li>
<li class="chapter" data-level="6.7.2" data-path="data2.html"><a href="data2.html#Ch6PP3"><i class="fa fa-check"></i><b>6.7.2</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="data2.html"><a href="data2.html#dplyr"><i class="fa fa-check"></i><b>6.8</b> Manipulating Data with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="data2.html"><a href="data2.html#improved-data-frames"><i class="fa fa-check"></i><b>6.8.1</b> Improved Data Frames</a></li>
<li class="chapter" data-level="6.8.2" data-path="data2.html"><a href="data2.html#filtering-data-by-row"><i class="fa fa-check"></i><b>6.8.2</b> Filtering Data by Row</a></li>
<li class="chapter" data-level="6.8.3" data-path="data2.html"><a href="data2.html#selecting-variables-by-column"><i class="fa fa-check"></i><b>6.8.3</b> Selecting variables by column</a></li>
<li class="chapter" data-level="6.8.4" data-path="data2.html"><a href="data2.html#ch6PP4"><i class="fa fa-check"></i><b>6.8.4</b> Practice Problem</a></li>
<li class="chapter" data-level="6.8.5" data-path="data2.html"><a href="data2.html#pipes"><i class="fa fa-check"></i><b>6.8.5</b> Pipes</a></li>
<li class="chapter" data-level="6.8.6" data-path="data2.html"><a href="data2.html#arranging-data-by-row"><i class="fa fa-check"></i><b>6.8.6</b> Arranging Data by Row</a></li>
<li class="chapter" data-level="6.8.7" data-path="data2.html"><a href="data2.html#ch6PP5"><i class="fa fa-check"></i><b>6.8.7</b> Practice Problem</a></li>
<li class="chapter" data-level="6.8.8" data-path="data2.html"><a href="data2.html#renaming-variables"><i class="fa fa-check"></i><b>6.8.8</b> Renaming Variables</a></li>
<li class="chapter" data-level="6.8.9" data-path="data2.html"><a href="data2.html#data-summaries-and-grouping"><i class="fa fa-check"></i><b>6.8.9</b> Data Summaries and Grouping</a></li>
<li class="chapter" data-level="6.8.10" data-path="data2.html"><a href="data2.html#creating-new-variables"><i class="fa fa-check"></i><b>6.8.10</b> Creating New Variables</a></li>
<li class="chapter" data-level="6.8.11" data-path="data2.html"><a href="data2.html#ch6PP6"><i class="fa fa-check"></i><b>6.8.11</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="data2.html"><a href="data2.html#ch6Ex"><i class="fa fa-check"></i><b>6.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>7</b> Functions and Programming</a>
<ul>
<li class="chapter" data-level="7.1" data-path="functions.html"><a href="functions.html#r-functions"><i class="fa fa-check"></i><b>7.1</b> R Functions</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="functions.html"><a href="functions.html#ch7PP1"><i class="fa fa-check"></i><b>7.1.1</b> Practice Problem</a></li>
<li class="chapter" data-level="7.1.2" data-path="functions.html"><a href="functions.html#creating-functions"><i class="fa fa-check"></i><b>7.1.2</b> Creating Functions</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="functions.html"><a href="functions.html#programming-conditional-statements"><i class="fa fa-check"></i><b>7.2</b> Programming: Conditional Statements</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="functions.html"><a href="functions.html#comparison-and-logical-operators"><i class="fa fa-check"></i><b>7.2.1</b> Comparison and Logical Operators</a></li>
<li class="chapter" data-level="7.2.2" data-path="functions.html"><a href="functions.html#if-else-statements"><i class="fa fa-check"></i><b>7.2.2</b> If else statements</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="functions.html"><a href="functions.html#arith"><i class="fa fa-check"></i><b>7.3</b> Computer Arithmetic</a></li>
<li class="chapter" data-level="7.4" data-path="functions.html"><a href="functions.html#loops"><i class="fa fa-check"></i><b>7.4</b> Loops</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="functions.html"><a href="functions.html#a-repeat-loop"><i class="fa fa-check"></i><b>7.4.1</b> A Repeat Loop</a></li>
<li class="chapter" data-level="7.4.2" data-path="functions.html"><a href="functions.html#a-while-loop"><i class="fa fa-check"></i><b>7.4.2</b> A While Loop</a></li>
<li class="chapter" data-level="7.4.3" data-path="functions.html"><a href="functions.html#a-for-loop"><i class="fa fa-check"></i><b>7.4.3</b> A For Loop</a></li>
<li class="chapter" data-level="7.4.4" data-path="functions.html"><a href="functions.html#ch7PP2"><i class="fa fa-check"></i><b>7.4.4</b> Practice Problem</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="functions.html"><a href="functions.html#efficiency-considerations"><i class="fa fa-check"></i><b>7.5</b> Efficiency Considerations</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="functions.html"><a href="functions.html#growing-objects"><i class="fa fa-check"></i><b>7.5.1</b> Growing Objects</a></li>
<li class="chapter" data-level="7.5.2" data-path="functions.html"><a href="functions.html#vectorization"><i class="fa fa-check"></i><b>7.5.2</b> Vectorization</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="functions.html"><a href="functions.html#more-on-functions"><i class="fa fa-check"></i><b>7.6</b> More on Functions</a></li>
<li class="chapter" data-level="7.7" data-path="functions.html"><a href="functions.html#calling-functions"><i class="fa fa-check"></i><b>7.7</b> Calling Functions</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="functions.html"><a href="functions.html#the-...-argument"><i class="fa fa-check"></i><b>7.7.1</b> The <code>...</code> argument</a></li>
<li class="chapter" data-level="7.7.2" data-path="functions.html"><a href="functions.html#lazy-evaluation"><i class="fa fa-check"></i><b>7.7.2</b> Lazy Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="functions.html"><a href="functions.html#ch7Ex"><i class="fa fa-check"></i><b>7.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="sp.html"><a href="sp.html"><i class="fa fa-check"></i><b>8</b> Spatial Data Visualization and Analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sp.html"><a href="sp.html#overview"><i class="fa fa-check"></i><b>8.1</b> Overview</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="sp.html"><a href="sp.html#some-spatial-data-packages"><i class="fa fa-check"></i><b>8.1.1</b> Some Spatial Data Packages</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sp.html"><a href="sp.html#motivating-data"><i class="fa fa-check"></i><b>8.2</b> Motivating Data</a></li>
<li class="chapter" data-level="8.3" data-path="sp.html"><a href="sp.html#reading-spatial-data-into-r"><i class="fa fa-check"></i><b>8.3</b> Reading Spatial Data into R</a></li>
<li class="chapter" data-level="8.4" data-path="sp.html"><a href="sp.html#coordinate-reference-systems"><i class="fa fa-check"></i><b>8.4</b> Coordinate Reference Systems</a></li>
<li class="chapter" data-level="8.5" data-path="sp.html"><a href="sp.html#ggmap"><i class="fa fa-check"></i><b>8.5</b> Illustration using <code>ggmap</code></a></li>
<li class="chapter" data-level="8.6" data-path="sp.html"><a href="sp.html#illustration-using-leaflet"><i class="fa fa-check"></i><b>8.6</b> Illustration using <code>leaflet</code></a></li>
<li class="chapter" data-level="8.7" data-path="sp.html"><a href="sp.html#subsetting-spatial-data"><i class="fa fa-check"></i><b>8.7</b> Subsetting Spatial Data</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="sp.html"><a href="sp.html#fetching-and-cropping-data-using-raster"><i class="fa fa-check"></i><b>8.7.1</b> Fetching and Cropping Data using <code>raster</code></a></li>
<li class="chapter" data-level="8.7.2" data-path="sp.html"><a href="sp.html#logical-index-and-name-subsetting"><i class="fa fa-check"></i><b>8.7.2</b> Logical, Index, and Name Subsetting</a></li>
<li class="chapter" data-level="8.7.3" data-path="sp.html"><a href="sp.html#spatial-subsetting-and-overlay"><i class="fa fa-check"></i><b>8.7.3</b> Spatial Subsetting and Overlay</a></li>
<li class="chapter" data-level="8.7.4" data-path="sp.html"><a href="sp.html#spatial-aggregation"><i class="fa fa-check"></i><b>8.7.4</b> Spatial Aggregation</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="sp.html"><a href="sp.html#where-to-go-from-here"><i class="fa fa-check"></i><b>8.8</b> Where to go from here</a></li>
<li class="chapter" data-level="8.9" data-path="sp.html"><a href="sp.html#spEx"><i class="fa fa-check"></i><b>8.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html"><i class="fa fa-check"></i><b>9</b> Shiny: Interactive Web Apps in R</a>
<ul>
<li class="chapter" data-level="9.1" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#running-a-simple-shiny-app"><i class="fa fa-check"></i><b>9.1</b> Running a Simple Shiny App</a></li>
<li class="chapter" data-level="9.2" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#adding-user-input"><i class="fa fa-check"></i><b>9.2</b> Adding User Input</a></li>
<li class="chapter" data-level="9.3" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#adding-output"><i class="fa fa-check"></i><b>9.3</b> Adding Output</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#interactive-server-logic"><i class="fa fa-check"></i><b>9.3.1</b> Interactive Server Logic</a></li>
<li class="chapter" data-level="9.3.2" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#interactive-user-interface"><i class="fa fa-check"></i><b>9.3.2</b> Interactive User Interface</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#more-advanced-shiny-app-michigan-campgrounds"><i class="fa fa-check"></i><b>9.4</b> More Advanced Shiny App: Michigan Campgrounds</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#michigan-campgrounds-ui"><i class="fa fa-check"></i><b>9.4.1</b> Michigan Campgrounds UI</a></li>
<li class="chapter" data-level="9.4.2" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#michigan-campgrounds-server-logic"><i class="fa fa-check"></i><b>9.4.2</b> Michigan Campgrounds Server Logic</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#adding-leaflet-to-shiny"><i class="fa fa-check"></i><b>9.5</b> Adding Leaflet to Shiny</a></li>
<li class="chapter" data-level="9.6" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#why-use-shiny"><i class="fa fa-check"></i><b>9.6</b> Why use Shiny?</a></li>
<li class="chapter" data-level="9.7" data-path="shiny-interactive-web-apps-in-r.html"><a href="shiny-interactive-web-apps-in-r.html#shinyEx"><i class="fa fa-check"></i><b>9.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>10</b> Classification</a>
<ul>
<li class="chapter" data-level="10.1" data-path="classification.html"><a href="classification.html#logistic-regression"><i class="fa fa-check"></i><b>10.1</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="classification.html"><a href="classification.html#adding-predictors"><i class="fa fa-check"></i><b>10.1.1</b> Adding Predictors</a></li>
<li class="chapter" data-level="10.1.2" data-path="classification.html"><a href="classification.html#more-than-two-classes"><i class="fa fa-check"></i><b>10.1.2</b> More than Two Classes</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="classification.html"><a href="classification.html#nearest-neighbor-methods"><i class="fa fa-check"></i><b>10.2</b> Nearest Neighbor Methods</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="classification.html"><a href="classification.html#knn-and-the-diabetes-data"><i class="fa fa-check"></i><b>10.2.1</b> kNN and the Diabetes Data</a></li>
<li class="chapter" data-level="10.2.2" data-path="classification.html"><a href="classification.html#classPP1"><i class="fa fa-check"></i><b>10.2.2</b> Practice Problem</a></li>
<li class="chapter" data-level="10.2.3" data-path="classification.html"><a href="classification.html#knn-and-the-iris-data"><i class="fa fa-check"></i><b>10.2.3</b> kNN and the iris Data</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="classification.html"><a href="classification.html#exClass"><i class="fa fa-check"></i><b>10.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="xml.html"><a href="xml.html"><i class="fa fa-check"></i><b>11</b> Text Data</a>
<ul>
<li class="chapter" data-level="11.1" data-path="xml.html"><a href="xml.html#reading-text-data-into-r"><i class="fa fa-check"></i><b>11.1</b> Reading Text Data into R</a></li>
<li class="chapter" data-level="11.2" data-path="xml.html"><a href="xml.html#the-paste-function"><i class="fa fa-check"></i><b>11.2</b> The <code>paste</code> Function</a></li>
<li class="chapter" data-level="11.3" data-path="xml.html"><a href="xml.html#more-string-processing-functions"><i class="fa fa-check"></i><b>11.3</b> More String Processing Functions</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="xml.html"><a href="xml.html#tolower-and-toupper"><i class="fa fa-check"></i><b>11.3.1</b> <code>tolower</code> and <code>toupper</code></a></li>
<li class="chapter" data-level="11.3.2" data-path="xml.html"><a href="xml.html#nchar-and-strsplit"><i class="fa fa-check"></i><b>11.3.2</b> <code>nchar</code> and <code>strsplit</code></a></li>
<li class="chapter" data-level="11.3.3" data-path="xml.html"><a href="xml.html#textPP1"><i class="fa fa-check"></i><b>11.3.3</b> Practice Problem</a></li>
<li class="chapter" data-level="11.3.4" data-path="xml.html"><a href="xml.html#nchar-again"><i class="fa fa-check"></i><b>11.3.4</b> <code>nchar</code> Again</a></li>
<li class="chapter" data-level="11.3.5" data-path="xml.html"><a href="xml.html#textPP2"><i class="fa fa-check"></i><b>11.3.5</b> Practice Problem</a></li>
<li class="chapter" data-level="11.3.6" data-path="xml.html"><a href="xml.html#substr-and-strtrim"><i class="fa fa-check"></i><b>11.3.6</b> <code>substr</code> and <code>strtrim</code></a></li>
<li class="chapter" data-level="11.3.7" data-path="xml.html"><a href="xml.html#grep-and-related-functions"><i class="fa fa-check"></i><b>11.3.7</b> <code>grep</code> and Related Functions</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="xml.html"><a href="xml.html#textEx"><i class="fa fa-check"></i><b>11.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="rcpp.html"><a href="rcpp.html"><i class="fa fa-check"></i><b>12</b> Rcpp</a>
<ul>
<li class="chapter" data-level="12.1" data-path="rcpp.html"><a href="rcpp.html#getting-started-with-rcpp"><i class="fa fa-check"></i><b>12.1</b> Getting Started with Rcpp</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="rcpp.html"><a href="rcpp.html#installation"><i class="fa fa-check"></i><b>12.1.1</b> Installation</a></li>
<li class="chapter" data-level="12.1.2" data-path="rcpp.html"><a href="rcpp.html#the-simplest-c-example"><i class="fa fa-check"></i><b>12.1.2</b> The Simplest C++ Example</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="rcpp.html"><a href="rcpp.html#using-rcpp"><i class="fa fa-check"></i><b>12.2</b> Using Rcpp</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="rcpp.html"><a href="rcpp.html#exporting-c-functions"><i class="fa fa-check"></i><b>12.2.1</b> Exporting C++ Functions</a></li>
<li class="chapter" data-level="12.2.2" data-path="rcpp.html"><a href="rcpp.html#inline-c-code"><i class="fa fa-check"></i><b>12.2.2</b> Inline C++ Code</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="rcpp.html"><a href="rcpp.html#the-rcpp-interface"><i class="fa fa-check"></i><b>12.3</b> The Rcpp Interface</a></li>
<li class="chapter" data-level="12.4" data-path="rcpp.html"><a href="rcpp.html#no-input-and-scalar-output"><i class="fa fa-check"></i><b>12.4</b> No input and scalar output</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="rcpp.html"><a href="rcpp.html#scalar-input-and-scalar-output"><i class="fa fa-check"></i><b>12.4.1</b> Scalar input and scalar output</a></li>
<li class="chapter" data-level="12.4.2" data-path="rcpp.html"><a href="rcpp.html#vector-input-and-scalar-output"><i class="fa fa-check"></i><b>12.4.2</b> Vector input and scalar output</a></li>
<li class="chapter" data-level="12.4.3" data-path="rcpp.html"><a href="rcpp.html#vector-input-and-vector-output"><i class="fa fa-check"></i><b>12.4.3</b> Vector input and vector output</a></li>
<li class="chapter" data-level="12.4.4" data-path="rcpp.html"><a href="rcpp.html#matrix-input-and-vector-output"><i class="fa fa-check"></i><b>12.4.4</b> Matrix input and vector output</a></li>
<li class="chapter" data-level="12.4.5" data-path="rcpp.html"><a href="rcpp.html#matrix-input-and-matrix-output"><i class="fa fa-check"></i><b>12.4.5</b> Matrix input and matrix output</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="rcpp.html"><a href="rcpp.html#exCPP"><i class="fa fa-check"></i><b>12.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="databases-and-r.html"><a href="databases-and-r.html"><i class="fa fa-check"></i><b>13</b> Databases and R</a>
<ul>
<li class="chapter" data-level="13.1" data-path="databases-and-r.html"><a href="databases-and-r.html#sql-and-database-structure"><i class="fa fa-check"></i><b>13.1</b> SQL and Database Structure</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="databases-and-r.html"><a href="databases-and-r.html#sql"><i class="fa fa-check"></i><b>13.1.1</b> SQL</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="databases-and-r.html"><a href="databases-and-r.html#difficulties-of-working-with-large-datasets"><i class="fa fa-check"></i><b>13.2</b> Difficulties of Working with Large Datasets</a></li>
<li class="chapter" data-level="13.3" data-path="databases-and-r.html"><a href="databases-and-r.html#using-dplyr-to-query-the-database"><i class="fa fa-check"></i><b>13.3</b> Using <code>dplyr</code> to Query the Database</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="databases-and-r.html"><a href="databases-and-r.html#example-with-rsqlite"><i class="fa fa-check"></i><b>13.3.1</b> Example with RSQLite</a></li>
<li class="chapter" data-level="13.3.2" data-path="databases-and-r.html"><a href="databases-and-r.html#dbplot"><i class="fa fa-check"></i><b>13.3.2</b> <code>dbplot</code></a></li>
<li class="chapter" data-level="13.3.3" data-path="databases-and-r.html"><a href="databases-and-r.html#using-google-bigquery"><i class="fa fa-check"></i><b>13.3.3</b> Using Google BigQuery</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="databases-and-r.html"><a href="databases-and-r.html#changing-records-in-the-database"><i class="fa fa-check"></i><b>13.4</b> Changing Records in the Database</a></li>
<li class="chapter" data-level="13.5" data-path="databases-and-r.html"><a href="databases-and-r.html#r-studio-connections-pane"><i class="fa fa-check"></i><b>13.5</b> R Studio Connections Pane</a></li>
<li class="chapter" data-level="13.6" data-path="databases-and-r.html"><a href="databases-and-r.html#further-resources"><i class="fa fa-check"></i><b>13.6</b> Further Resources</a></li>
<li class="chapter" data-level="13.7" data-path="databases-and-r.html"><a href="databases-and-r.html#exDatabases"><i class="fa fa-check"></i><b>13.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html"><i class="fa fa-check"></i><b>14</b> Digital Signal Processing</a>
<ul>
<li class="chapter" data-level="14.1" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html#introduction-to-digital-signal-processing"><i class="fa fa-check"></i><b>14.1</b> Introduction to Digital Signal Processing</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html#sinusoidal-signals"><i class="fa fa-check"></i><b>14.1.1</b> Sinusoidal Signals</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html#noise-and-filters"><i class="fa fa-check"></i><b>14.2</b> Noise and Filters</a></li>
<li class="chapter" data-level="14.3" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html#fourier-transforms-and-spectrograms"><i class="fa fa-check"></i><b>14.3</b> Fourier Transforms and Spectrograms</a></li>
<li class="chapter" data-level="14.4" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html#analyzing-audio-data-with-warbler"><i class="fa fa-check"></i><b>14.4</b> Analyzing Audio Data with <code>warbleR</code></a></li>
<li class="chapter" data-level="14.5" data-path="digital-signal-processing.html"><a href="digital-signal-processing.html#exDSP"><i class="fa fa-check"></i><b>14.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="graphics.html"><a href="graphics.html"><i class="fa fa-check"></i><b>15</b> Graphics in R Part 2: <code>graphics</code></a>
<ul>
<li class="chapter" data-level="15.1" data-path="graphics.html"><a href="graphics.html#graphics1"><i class="fa fa-check"></i><b>15.1</b> Scatter Plots</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="graphics.html"><a href="graphics.html#graphics2"><i class="fa fa-check"></i><b>15.1.1</b> Adding lines to a scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="graphics.html"><a href="graphics.html#graphics3"><i class="fa fa-check"></i><b>15.2</b> Labels, Axes, Text, etc.</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="graphics.html"><a href="graphics.html#graphics4"><i class="fa fa-check"></i><b>15.2.1</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="graphics.html"><a href="graphics.html#graphics5"><i class="fa fa-check"></i><b>15.3</b> Customizing Axes</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="graphics.html"><a href="graphics.html#graphics6"><i class="fa fa-check"></i><b>15.3.1</b> Text, Point Size, and Color</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="graphics.html"><a href="graphics.html#graphics7"><i class="fa fa-check"></i><b>15.4</b> Other Types of Graphics</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="graphics.html"><a href="graphics.html#graphics8"><i class="fa fa-check"></i><b>15.4.1</b> Histograms</a></li>
<li class="chapter" data-level="15.4.2" data-path="graphics.html"><a href="graphics.html#graphics9"><i class="fa fa-check"></i><b>15.4.2</b> Boxplots</a></li>
<li class="chapter" data-level="15.4.3" data-path="graphics.html"><a href="graphics.html#graphics10"><i class="fa fa-check"></i><b>15.4.3</b> Bar Graphs</a></li>
<li class="chapter" data-level="15.4.4" data-path="graphics.html"><a href="graphics.html#graphics11"><i class="fa fa-check"></i><b>15.4.4</b> Graphs of Functions</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="graphics.html"><a href="graphics.html#graphics12"><i class="fa fa-check"></i><b>15.5</b> Saving Graphics</a></li>
<li class="chapter" data-level="15.6" data-path="graphics.html"><a href="graphics.html#graphics13"><i class="fa fa-check"></i><b>15.6</b> A Summary of Useful <code>graphics</code> Functions and Arguments</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="graphics.html"><a href="graphics.html#graphics14"><i class="fa fa-check"></i><b>15.6.1</b> Practice Problem</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Programming for Data Sciences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="structures" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Data Structures</h1>
<p>A data structure is a format for organizing and storing data. The structure is designed so that data can be accessed and worked with in specific ways. Statistical software and programming languages have methods (or functions) designed to operate on different kinds of data structures.</p>
<p>This chapter’s focus is on data structures. To help initial understanding, the data in this chapter will be relatively modest in size and complexity. The ideas and methods, however, generalize to larger and more complex data sets.</p>
<p>The base data structures in R are vectors, matrices, arrays, data frames, and lists. The first three, vectors, matrices, and arrays, require all elements to be of the same type or homogeneous, e.g., all numeric or all character. Data frames and lists allow elements to be of different types or heterogeneous, e.g., some elements of a data frame may be numeric while other elements may be character. These base structures can also be organized by their dimensionality, i.e., 1-dimensional, 2-dimensional, or N-dimensional, as shown in Table <a href="structures.html#tab:dataStructures">4.1</a>.</p>
<table>
<caption>
<span id="tab:dataStructures">TABLE 4.1: </span>Dimension and type content of base data structures
in R
</caption>
<thead>
<tr>
<th style="text-align:left;">
Dimension
</th>
<th style="text-align:left;">
Homogeneous
</th>
<th style="text-align:left;">
Heterogeneous
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Atomic vector
</td>
<td style="text-align:left;">
List
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Matrix
</td>
<td style="text-align:left;">
Data frame
</td>
</tr>
<tr>
<td style="text-align:left;">
N
</td>
<td style="text-align:left;">
Array
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
<p>R has no scalar types, i.e., 0-dimensional. Individual numbers or strings are actually vectors of length one.</p>
<p>An efficient way to understand what comprises a given object is to use the <code>str()</code> function. <code>str()</code> is short for structure and prints a compact, human-readable description of any R data structure. For example, in the code below, we prove to ourselves that what we might think of as a scalar value is actually a vector of length one.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="structures.html#cb54-1"></a>a &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb54-2"><a href="structures.html#cb54-2"></a><span class="kw">str</span>(a)</span></code></pre></div>
<pre><code>##  num 1</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="structures.html#cb56-1"></a><span class="kw">is.vector</span>(a)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="structures.html#cb58-1"></a><span class="kw">length</span>(a)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Here we assigned <code>a</code> the scalar value one. The <code>str(a)</code> prints <code>num 1</code>, which says <code>a</code> is numeric of length one. Then just to be sure we used the function <code>is.vector()</code> to test if <code>a</code> is in fact a vector. Then, just for fun, we asked the length of <code>a</code>, which again returns one. There are a set of similar logical tests for the other base data structures, e.g., <code>is.matrix()</code>, <code>is.array()</code>, <code>is.data.frame()</code>, and <code>is.list()</code>. These will all come in handy as we encounter different R objects.</p>
<div id="vector" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Vectors</h2>
<p>Think of a vector<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a> as a structure to represent one variable in a data set. For example a vector might hold the weights, in pounds, of 7 people in a data set. Or another vector might hold the genders of those 7 people. The <code>c()</code> function in R is useful for creating (small) vectors and for modifying existing vectors. Think of <code>c</code> as standing for “combine”.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="structures.html#cb60-1"></a>weight &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">123</span>, <span class="dv">157</span>, <span class="dv">205</span>, <span class="dv">199</span>, <span class="dv">223</span>, <span class="dv">140</span>, <span class="dv">105</span>)</span>
<span id="cb60-2"><a href="structures.html#cb60-2"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 205 199 223 140 105</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="structures.html#cb62-1"></a>gender &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;female&quot;</span>, <span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>,</span>
<span id="cb62-2"><a href="structures.html#cb62-2"></a>            <span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>)</span>
<span id="cb62-3"><a href="structures.html#cb62-3"></a>gender</span></code></pre></div>
<pre><code>## [1] &quot;female&quot; &quot;female&quot; &quot;male&quot;   &quot;female&quot; &quot;male&quot;  
## [6] &quot;male&quot;   &quot;female&quot;</code></pre>
<p>Notice that elements of a vector are separated by commas when using the <code>c()</code> function to create a vector. Also notice that character values are placed inside quotation marks.</p>
<p>The <code>c()</code> function also can be used to add to an existing vector. For example, if an eighth male person was included in the data set, and his weight was 194 pounds, the existing vectors could be modified as follows.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="structures.html#cb64-1"></a>weight &lt;-<span class="st"> </span><span class="kw">c</span>(weight, <span class="dv">194</span>)</span>
<span id="cb64-2"><a href="structures.html#cb64-2"></a>gender &lt;-<span class="st"> </span><span class="kw">c</span>(gender, <span class="st">&quot;male&quot;</span>)</span>
<span id="cb64-3"><a href="structures.html#cb64-3"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 205 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="structures.html#cb66-1"></a>gender</span></code></pre></div>
<pre><code>## [1] &quot;female&quot; &quot;female&quot; &quot;male&quot;   &quot;female&quot; &quot;male&quot;  
## [6] &quot;male&quot;   &quot;female&quot; &quot;male&quot;</code></pre>
<div id="types-conversion-coercion" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Types, Conversion, Coercion</h3>
<p>Clearly it is important to distinguish between different types of vectors. For example, it makes sense to ask R to calculate the mean of the weights stored in <code>weight</code>, but does not make sense to ask R to compute the mean of the genders stored in <code>gender</code>. Vectors in R may have one of six different “types”: character, double, integer, logical, complex, and raw. Vectors in R may have one of six different “types”: character, double, integer, logical, complex, and raw. We will not encounter the complex and raw types in everyday data analysis, and so we focus on the first four data types.</p>
<ol style="list-style-type: decimal">
<li><code>character</code>: consists of letters or words. Our vector <code>gender</code> is a character vector because it consists of the genders for each person in our dataset.</li>
</ol>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="structures.html#cb68-1"></a><span class="kw">typeof</span>(gender)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><code>double</code>: a numeric object that can be an integer or non-integer value (e.g., 10, 4.2). Our vector <code>weight</code> is a double vector.</li>
</ol>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="structures.html#cb70-1"></a><span class="kw">typeof</span>(weight)</span></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><code>integer</code>: a numeric object that can only be an integer. It may be surprising to see the weight variable <code>weight</code> is of type <code>double</code>, even though its values are all integers. By default, R creates a double type vector when numeric values are given via the <code>c</code> function. We can create an integer vector of weight variables by placing the letter <code>L</code> next to each of the numbers when we place it in the vector:</li>
</ol>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="structures.html#cb72-1"></a>weight.int &lt;-<span class="st"> </span><span class="kw">c</span>(123L, 157L, 205L, 199L, 223L, 140L, 105L, 194L)</span>
<span id="cb72-2"><a href="structures.html#cb72-2"></a><span class="kw">typeof</span>(weight.int)</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<ol start="4" style="list-style-type: decimal">
<li><code>logical</code>: used to represent variables that can take values <code>TRUE</code> or <code>FALSE</code>. To illustrate logical vectors, imagine that each of the eight people in the data setwas asked whether they were taking blood pressure medication, and the responses were coded as <code>TRUE</code> if the person answered yes, and <code>FALSE</code> if the person answered no.</li>
</ol>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="structures.html#cb74-1"></a>bp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>)</span>
<span id="cb74-2"><a href="structures.html#cb74-2"></a>bp</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="structures.html#cb76-1"></a><span class="kw">typeof</span>(bp)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<p>When it makes sense, it is possible to convert vectors to a different type. Consider the following examples.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="structures.html#cb78-1"></a>weight.int &lt;-<span class="st"> </span><span class="kw">as.integer</span>(weight)</span>
<span id="cb78-2"><a href="structures.html#cb78-2"></a>weight.int</span></code></pre></div>
<pre><code>## [1] 123 157 205 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="structures.html#cb80-1"></a><span class="kw">typeof</span>(weight.int)</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="structures.html#cb82-1"></a>weight.char &lt;-<span class="st"> </span><span class="kw">as.character</span>(weight)</span>
<span id="cb82-2"><a href="structures.html#cb82-2"></a>weight.char</span></code></pre></div>
<pre><code>## [1] &quot;123&quot; &quot;157&quot; &quot;205&quot; &quot;199&quot; &quot;223&quot; &quot;140&quot; &quot;105&quot; &quot;194&quot;</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="structures.html#cb84-1"></a>bp.double &lt;-<span class="st"> </span><span class="kw">as.double</span>(bp)</span>
<span id="cb84-2"><a href="structures.html#cb84-2"></a>bp.double</span></code></pre></div>
<pre><code>## [1] 1 1 0 1 0 0 1 1</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="structures.html#cb86-1"></a>gender.oops &lt;-<span class="st"> </span><span class="kw">as.double</span>(gender)</span></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="structures.html#cb88-1"></a>gender.oops</span></code></pre></div>
<pre><code>## [1] NA NA NA NA NA NA NA NA</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="structures.html#cb90-1"></a><span class="kw">sum</span>(bp)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>The integer version of <code>weight</code> doesn’t look any different, but it is stored differently, which can be important both for computational efficiency and for interfacing with other languages such as <code>C++</code>. As noted above, however, we will not worry about the distinction between integer and double types. Converting <code>weight</code> to character goes as expected: The character representations of the numbers replace the numbers themselves. Converting the logical vector <code>bp</code> to double is pretty straightforward too: <code>FALSE</code> is converted to zero, and <code>TRUE</code> is converted to one. Now think about converting the character vector <code>gender</code> to a numeric double vector. It’s not at all clear how to represent “female” and “male” as numbers. In fact in this case what R does is to create a character vector, but with each element set to <code>NA</code>, which is the representation of missing data.<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a> Finally consider the code <code>sum(bp)</code>. Now <code>bp</code> is a logical vector, but when R sees that we are asking to sum this logical vector, it automatically converts it to a numerical vector and then adds the zeros and ones representing <code>FALSE</code> and <code>TRUE</code>.</p>
<p>R also has functions to test whether a vector is of a particular type.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="structures.html#cb92-1"></a><span class="kw">is.double</span>(weight)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="structures.html#cb94-1"></a><span class="kw">is.character</span>(weight)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="structures.html#cb96-1"></a><span class="kw">is.integer</span>(weight.int)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="structures.html#cb98-1"></a><span class="kw">is.logical</span>(bp)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div id="coercion" class="section level4" number="4.1.1.1">
<h4><span class="header-section-number">4.1.1.1</span> Coercion</h4>
<p>Consider the following examples.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="structures.html#cb100-1"></a>xx &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="ot">TRUE</span>)</span>
<span id="cb100-2"><a href="structures.html#cb100-2"></a>xx</span></code></pre></div>
<pre><code>## [1] 1 2 3 1</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="structures.html#cb102-1"></a>yy &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="st">&quot;dog&quot;</span>)</span>
<span id="cb102-2"><a href="structures.html#cb102-2"></a>yy</span></code></pre></div>
<pre><code>## [1] &quot;1&quot;   &quot;2&quot;   &quot;3&quot;   &quot;dog&quot;</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="structures.html#cb104-1"></a>zz &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="st">&quot;cat&quot;</span>)</span>
<span id="cb104-2"><a href="structures.html#cb104-2"></a>zz</span></code></pre></div>
<pre><code>## [1] &quot;TRUE&quot;  &quot;FALSE&quot; &quot;cat&quot;</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="structures.html#cb106-1"></a>weight<span class="op">+</span>bp</span></code></pre></div>
<pre><code>## [1] 124 158 205 200 223 140 106 195</code></pre>
<p>Vectors in R can only contain elements of one type. If more than one type is included in a <code>c()</code> function, R silently <em>coerces</em> the vector to be of one type. The examples illustrate the hierarchy—if any element is a character, then the whole vector is character. If some elements are numeric (either integer or double) and other elements are logical, the whole vector is numeric. Note what happened when R was asked to add the numeric vector <code>weight</code> to the logical vector <code>bp</code>. The logical vector was silently coerced to be numeric, so that FALSE became zero and TRUE became one, and then the two numeric vectors were added.</p>
</div>
</div>
<div id="accessing-specific-elements-of-vectors" class="section level3" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Accessing Specific Elements of Vectors</h3>
<p>To access and possibly change specific elements of vectors, refer to the position of the element in square brackets. For example, <code>weight[4]</code> refers to the fourth element of the vector <code>weight</code>. Note that R starts the numbering of elements at 1, i.e., the first element of a vector <code>x</code> is <code>x[1]</code>.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="structures.html#cb108-1"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 205 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="structures.html#cb110-1"></a>weight[<span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 223</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="structures.html#cb112-1"></a>weight[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 123 157 205</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="structures.html#cb114-1"></a><span class="kw">length</span>(weight)</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="structures.html#cb116-1"></a>weight[<span class="kw">length</span>(weight)]</span></code></pre></div>
<pre><code>## [1] 194</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="structures.html#cb118-1"></a>weight[]</span></code></pre></div>
<pre><code>## [1] 123 157 205 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="structures.html#cb120-1"></a>weight[<span class="dv">3</span>] &lt;-<span class="st"> </span><span class="dv">202</span></span>
<span id="cb120-2"><a href="structures.html#cb120-2"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<p>Note that including nothing in the square brackets results in the whole vector being returned.</p>
<p>Negative numbers in the square brackets tell R to omit the corresponding value. And a zero as a subscript returns nothing (more precisely, it returns a length zero vector of the appropriate type).</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="structures.html#cb122-1"></a>weight[<span class="op">-</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 123 157 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="structures.html#cb124-1"></a>weight[<span class="op">-</span><span class="kw">length</span>(weight)]</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="structures.html#cb126-1"></a>lessWeight &lt;-<span class="st"> </span>weight[<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>)]</span>
<span id="cb126-2"><a href="structures.html#cb126-2"></a>lessWeight</span></code></pre></div>
<pre><code>## [1] 157 199 140 105 194</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="structures.html#cb128-1"></a>weight[<span class="dv">0</span>]</span></code></pre></div>
<pre><code>## numeric(0)</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="structures.html#cb130-1"></a>weight[<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>)]</span></code></pre></div>
<pre><code>## [1] 157 123</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="structures.html#cb132-1"></a>weight[<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">2</span>)]</span></code></pre></div>
<pre><code>## Error in weight[c(-1, 2)]: only 0&#39;s may be mixed with negative subscripts</code></pre>
<p>Note that mixing zero and other nonzero subscripts is allowed, but mixing negative and positive subscripts is not allowed.</p>
<p>What about the (usual) case where we don’t know the positions of the elements we want? For example possibly we want the weights of all females in the data. Later we will learn how to subset using logical indices, which is a very powerful way to access desired elements of a vector.</p>
</div>
<div id="ch4PP1" class="section level3" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Practice Problem</h3>
<p>A bad programming technique that often plagues beginners is a technique called <em>hardcoding</em>. Consider the following simple vector containing data on the number of tree species found at different sites.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="structures.html#cb134-1"></a>tree.sp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">15</span>, <span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">9</span>, <span class="dv">11</span>)</span></code></pre></div>
<p>Suppose we are interested in the second to last value of the data set. One way to do this is to first determine the length of vector using the <code>length()</code> function, then taking that value and subtracting 1.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="structures.html#cb135-1"></a>num.sites &lt;-<span class="st"> </span><span class="kw">length</span>(tree.sp)</span>
<span id="cb135-2"><a href="structures.html#cb135-2"></a>num.sites</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="structures.html#cb137-1"></a>tree.sp[<span class="dv">10</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>This is an example of <em>hardcoding</em>. But what if we attempt to use the same code on a second vector of tree species data that has a different number of sites?</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="structures.html#cb139-1"></a>tree.sp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">19</span>, <span class="dv">3</span>)</span>
<span id="cb139-2"><a href="structures.html#cb139-2"></a>num.sites &lt;-<span class="st"> </span><span class="kw">length</span>(tree.sp)</span>
<span id="cb139-3"><a href="structures.html#cb139-3"></a>num.sites</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="structures.html#cb141-1"></a>tree.sp[<span class="dv">10</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>That’s clearly not what we want. Fix this code so we can always extract the second to last value in the vector, regardless of the length of the vector.</p>
</div>
</div>
<div id="factors" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Factors</h2>
<p>Categorical variables can be represented as character vectors. In many cases this simple representation is sufficient. Consider, however, two other categorical variables, one representing age via categories <code>youth</code>, <code>young adult</code>, <code>middle age</code>, <code>senior</code>, and another representing income via categories <code>lower</code>, <code>middle</code>, and <code>upper</code>. Suppose that for the small health data set, all the people are either middle aged or senior citizens. If we just represented the variable via a character vector, there would be no way to know that there are two other categories, representing youth and young adults, which happen not to be present in the data set. And for the income variable, the character vector representation does not explicitly indicate that there is an ordering of the levels.</p>
<p>Factors in R provide a more sophisticated way to represent categorical variables. Factors explicitly contain all possible levels, and allow ordering of levels.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="structures.html#cb143-1"></a>age &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;middle age&quot;</span>, <span class="st">&quot;senior&quot;</span>, <span class="st">&quot;middle age&quot;</span>, <span class="st">&quot;senior&quot;</span>,</span>
<span id="cb143-2"><a href="structures.html#cb143-2"></a>         <span class="st">&quot;senior&quot;</span>, <span class="st">&quot;senior&quot;</span>, <span class="st">&quot;senior&quot;</span>, <span class="st">&quot;middle age&quot;</span>)</span>
<span id="cb143-3"><a href="structures.html#cb143-3"></a>income &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;lower&quot;</span>, <span class="st">&quot;lower&quot;</span>, <span class="st">&quot;upper&quot;</span>, <span class="st">&quot;middle&quot;</span>, <span class="st">&quot;upper&quot;</span>,</span>
<span id="cb143-4"><a href="structures.html#cb143-4"></a>            <span class="st">&quot;lower&quot;</span>, <span class="st">&quot;lower&quot;</span>, <span class="st">&quot;middle&quot;</span>)</span>
<span id="cb143-5"><a href="structures.html#cb143-5"></a>age</span></code></pre></div>
<pre><code>## [1] &quot;middle age&quot; &quot;senior&quot;     &quot;middle age&quot; &quot;senior&quot;    
## [5] &quot;senior&quot;     &quot;senior&quot;     &quot;senior&quot;     &quot;middle age&quot;</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="structures.html#cb145-1"></a>income</span></code></pre></div>
<pre><code>## [1] &quot;lower&quot;  &quot;lower&quot;  &quot;upper&quot;  &quot;middle&quot; &quot;upper&quot; 
## [6] &quot;lower&quot;  &quot;lower&quot;  &quot;middle&quot;</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="structures.html#cb147-1"></a>age &lt;-<span class="st"> </span><span class="kw">factor</span>(age, <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">&quot;youth&quot;</span>, <span class="st">&quot;young adult&quot;</span>, <span class="st">&quot;middle age&quot;</span>,</span>
<span id="cb147-2"><a href="structures.html#cb147-2"></a>                            <span class="st">&quot;senior&quot;</span>))</span>
<span id="cb147-3"><a href="structures.html#cb147-3"></a>age</span></code></pre></div>
<pre><code>## [1] middle age senior     middle age senior    
## [5] senior     senior     senior     middle age
## Levels: youth young adult middle age senior</code></pre>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="structures.html#cb149-1"></a>income &lt;-<span class="st"> </span><span class="kw">factor</span>(income, <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">&quot;lower&quot;</span>, <span class="st">&quot;middle&quot;</span>, <span class="st">&quot;upper&quot;</span>),</span>
<span id="cb149-2"><a href="structures.html#cb149-2"></a>                 <span class="dt">ordered =</span> <span class="ot">TRUE</span>)</span>
<span id="cb149-3"><a href="structures.html#cb149-3"></a>income</span></code></pre></div>
<pre><code>## [1] lower  lower  upper  middle upper  lower  lower 
## [8] middle
## Levels: lower &lt; middle &lt; upper</code></pre>
<p>In the factor version of <code>age</code> the levels are explicitly listed, so it is clear that the two included levels are not all the possible levels. And in the factor version of income, the ordering is explicit.</p>
<p>In many cases the character vector representation of a categorical variable is sufficient and easier to work with. In this book, factors will not be used extensively. It is important to note that R often by default creates a factor when character data are read in, and sometimes it is necessary to use the argument <code>stringsAsFactors = FALSE</code> to explicitly tell R not to do this. This is shown later in the chapter when data frames are introduced.</p>
</div>
<div id="missing-data-infinity-etc." class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Missing Data, Infinity, etc.</h2>
<p>Most real-world data sets have variables where some observations are missing. In a longitudinal study participants may drop out. In a survey, participants may decide not to respond to certain questions. Statistical software should be able to represent missing data and to analyze data sets in which some data are missing.</p>
<p>In R, the value <code>NA</code> is used for a missing data value. Since missing values may occur in numeric, character, and other types of data, and since R requires that a vector contain only elements of one type, there are different types of <code>NA</code> values. Usually R determines the appropriate type of <code>NA</code> value automatically. It is worth noting that the default type for <code>NA</code> is logical, and that <code>NA</code> is NOT the same as the character string <code>"NA"</code>.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="structures.html#cb151-1"></a>missingCharacter &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;dog&quot;</span>, <span class="st">&quot;cat&quot;</span>, <span class="ot">NA</span>, <span class="st">&quot;pig&quot;</span>, <span class="ot">NA</span>, <span class="st">&quot;horse&quot;</span>)</span>
<span id="cb151-2"><a href="structures.html#cb151-2"></a>missingCharacter</span></code></pre></div>
<pre><code>## [1] &quot;dog&quot;   &quot;cat&quot;   NA      &quot;pig&quot;   NA      &quot;horse&quot;</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="structures.html#cb153-1"></a><span class="kw">is.na</span>(missingCharacter)</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE FALSE  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="structures.html#cb155-1"></a>missingCharacter &lt;-<span class="st"> </span><span class="kw">c</span>(missingCharacter, <span class="st">&quot;NA&quot;</span>)</span>
<span id="cb155-2"><a href="structures.html#cb155-2"></a>missingCharacter</span></code></pre></div>
<pre><code>## [1] &quot;dog&quot;   &quot;cat&quot;   NA      &quot;pig&quot;   NA      &quot;horse&quot;
## [7] &quot;NA&quot;</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="structures.html#cb157-1"></a><span class="kw">is.na</span>(missingCharacter)</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="structures.html#cb159-1"></a>allMissing &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">NA</span>, <span class="ot">NA</span>, <span class="ot">NA</span>)</span>
<span id="cb159-2"><a href="structures.html#cb159-2"></a><span class="kw">typeof</span>(allMissing)</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<p>How should missing data be treated in computations, such as finding the mean or standard deviation of a variable? One possibility is to return <code>NA</code>. Another is to remove the missing value(s) and then perform the computation.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="structures.html#cb161-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="ot">NA</span>,<span class="dv">5</span>))</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="structures.html#cb163-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="ot">NA</span>,<span class="dv">5</span>), <span class="dt">na.rm=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 2.75</code></pre>
<p>As this example shows, the default behavior for the <code>mean()</code> function is to return <code>NA</code>. If removal of the missing values and then computing the mean is desired, the argument <code>na.rm</code> is set to <code>TRUE</code>. Different R functions have different default behaviors, and there are other possible actions. Consulting the help for a function provides the details.</p>
<div id="ch4PP2" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Practice Problem</h3>
<p>Collecting data is often a messy process resulting in multiple errors in the data. Consider the following small vector representing the weights of 10 adults in pounds.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="structures.html#cb165-1"></a>my.weights &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">150</span>, <span class="dv">138</span>, <span class="dv">289</span>, <span class="dv">239</span>, <span class="dv">12</span>, <span class="dv">103</span>, <span class="dv">310</span>, <span class="dv">200</span>, <span class="dv">218</span>, <span class="dv">178</span>)</span></code></pre></div>
<p>As far as I know, it’s not possible for an adult to weigh 12 pounds, so that is most likely an error. Change this value to NA, and then find the standard deviation of the weights after removing the NA value.</p>
</div>
<div id="infinity-and-nan" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Infinity and NaN</h3>
<p>What happens if R code requests division by zero, or results in a number that is too large to be represented? Here are some examples.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="structures.html#cb166-1"></a><span class="op">&gt;</span><span class="st"> </span>x &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span><span class="dv">4</span></span>
<span id="cb166-2"><a href="structures.html#cb166-2"></a><span class="op">&gt;</span><span class="st"> </span>x</span></code></pre></div>
<pre><code>## [1] 0 1 2 3 4</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="structures.html#cb168-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>x</span></code></pre></div>
<pre><code>## [1]    Inf 1.0000 0.5000 0.3333 0.2500</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="structures.html#cb170-1"></a><span class="op">&gt;</span><span class="st"> </span>x<span class="op">/</span>x</span></code></pre></div>
<pre><code>## [1] NaN   1   1   1   1</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="structures.html#cb172-1"></a><span class="op">&gt;</span><span class="st"> </span>y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">1000</span>, <span class="dv">10000</span>)</span>
<span id="cb172-2"><a href="structures.html#cb172-2"></a><span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span><span class="op">^</span>y</span></code></pre></div>
<pre><code>## [1]  1.024e+03 1.072e+301        Inf</code></pre>
<p><code>Inf</code> and <code>-Inf</code> represent infinity and negative infinity (and numbers which are too large in magnitude to be represented as floating point numbers). <code>NaN</code> represents the result of a calculation where the result is undefined, such as dividing zero by zero. All of these are common to a variety of programming languages, including R.</p>
</div>
</div>
<div id="dataFrames" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Data Frames</h2>
<p>Commonly, data is rectangular in form, with variables as columns and cases as rows. Continuing with the (contrived) data on weight, gender, and blood pressure medication, each of those variables would be a column of the data set, and each person’s measurements would be a row. In R, such data are represented as a <em>data frame</em>.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="structures.html#cb174-1"></a>healthData &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Weight =</span> weight, <span class="dt">Gender=</span>gender, <span class="dt">bp.meds =</span> bp,</span>
<span id="cb174-2"><a href="structures.html#cb174-2"></a>                         <span class="dt">stringsAsFactors=</span><span class="ot">FALSE</span>)</span>
<span id="cb174-3"><a href="structures.html#cb174-3"></a>healthData</span></code></pre></div>
<pre><code>##   Weight Gender bp.meds
## 1    123 female    TRUE
## 2    157 female    TRUE
## 3    202   male   FALSE
## 4    199 female    TRUE
## 5    223   male   FALSE
## 6    140   male   FALSE
## 7    105 female    TRUE
## 8    194   male    TRUE</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="structures.html#cb176-1"></a><span class="kw">names</span>(healthData)</span></code></pre></div>
<pre><code>## [1] &quot;Weight&quot;  &quot;Gender&quot;  &quot;bp.meds&quot;</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="structures.html#cb178-1"></a><span class="kw">colnames</span>(healthData)</span></code></pre></div>
<pre><code>## [1] &quot;Weight&quot;  &quot;Gender&quot;  &quot;bp.meds&quot;</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="structures.html#cb180-1"></a><span class="kw">names</span>(healthData) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Wt&quot;</span>, <span class="st">&quot;Gdr&quot;</span>, <span class="st">&quot;bp&quot;</span>)</span>
<span id="cb180-2"><a href="structures.html#cb180-2"></a>healthData</span></code></pre></div>
<pre><code>##    Wt    Gdr    bp
## 1 123 female  TRUE
## 2 157 female  TRUE
## 3 202   male FALSE
## 4 199 female  TRUE
## 5 223   male FALSE
## 6 140   male FALSE
## 7 105 female  TRUE
## 8 194   male  TRUE</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="structures.html#cb182-1"></a><span class="kw">rownames</span>(healthData)</span></code></pre></div>
<pre><code>## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; &quot;5&quot; &quot;6&quot; &quot;7&quot; &quot;8&quot;</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="structures.html#cb184-1"></a><span class="kw">names</span>(healthData) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Weight&quot;</span>, <span class="st">&quot;Gender&quot;</span>, <span class="st">&quot;bp.meds&quot;</span>)</span></code></pre></div>
<p>The <code>data.frame</code> function can be used to create a data frame (although it’s more common to read a data frame into R from an external file, something that will be introduced later). The names of the variables in the data frame are given as arguments, as are the vectors of data that make up the variable’s values. The argument <code>stringsAsFactors=FALSE</code> asks R not to convert character vectors into factors. As of version <code>R 4.0.0</code>, <code>R</code> does not automatically convert character vectors into factors. However, up until this recent version, <code>R</code> would automatically convert strings to factors (i.e., <code>stringsAsFactors = TRUE</code>), and so to avoid confusion we will typically display <code>stringsAsFactors=FALSE</code> throughout most of the book. Names of the columns (variables) can be extracted and set via either <code>names</code> or <code>colnames</code>. In the example, the variable names are changed to <code>Wt, Gdr, bp</code> and then changed back to the original <code>Weight, Gender, bp.meds</code> in this way. Rows can be named also. In this case since specific row names were not provided, the default row names of <code>"1", "2"</code> etc. are used.</p>
<p>In the next example a built-in dataset called <code>mtcars</code> is made available by the <code>data</code> function, and then the first and last six rows are displayed using <code>head</code> and <code>tail</code>.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="structures.html#cb185-1"></a><span class="kw">data</span>(mtcars)</span>
<span id="cb185-2"><a href="structures.html#cb185-2"></a><span class="kw">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02
## Valiant           18.1   6  225 105 2.76 3.460 20.22
##                   vs am gear carb
## Mazda RX4          0  1    4    4
## Mazda RX4 Wag      0  1    4    4
## Datsun 710         1  1    4    1
## Hornet 4 Drive     1  0    3    1
## Hornet Sportabout  0  0    3    2
## Valiant            1  0    3    1</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="structures.html#cb187-1"></a><span class="kw">tail</span>(mtcars)</span></code></pre></div>
<pre><code>##                 mpg cyl  disp  hp drat    wt qsec vs
## Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.7  0
## Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.9  1
## Ford Pantera L 15.8   8 351.0 264 4.22 3.170 14.5  0
## Ferrari Dino   19.7   6 145.0 175 3.62 2.770 15.5  0
## Maserati Bora  15.0   8 301.0 335 3.54 3.570 14.6  0
## Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.6  1
##                am gear carb
## Porsche 914-2   1    5    2
## Lotus Europa    1    5    2
## Ford Pantera L  1    5    4
## Ferrari Dino    1    5    6
## Maserati Bora   1    5    8
## Volvo 142E      1    4    2</code></pre>
<p>Note that the <code>mtcars</code> data frame does have non-default row names which give the make and model of the cars.</p>
<div id="accessing-specific-elements-of-data-frames" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Accessing Specific Elements of Data Frames</h3>
<p>Data frames are two-dimensional, so to access a specific element (or elements) we need to specify both the row and column.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="structures.html#cb189-1"></a>mtcars[<span class="dv">1</span>,<span class="dv">4</span>]</span></code></pre></div>
<pre><code>## [1] 110</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="structures.html#cb191-1"></a>mtcars[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 160 160 108</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="structures.html#cb193-1"></a>mtcars[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>##               cyl disp
## Mazda RX4       6  160
## Mazda RX4 Wag   6  160
## Datsun 710      4  108</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="structures.html#cb195-1"></a>mtcars[,<span class="dv">1</span>]</span></code></pre></div>
<pre><code>##  [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2
## [11] 17.8 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9
## [21] 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
## [31] 15.0 21.4</code></pre>
<p>Note that <code>mtcars[,1]</code> returns ALL elements in the first column. This agrees with the behavior for vectors, where leaving a subscript out of the square brackets tells R to return all values. In this case we are telling R to return all rows, and the first column.</p>
<p>For a data frame there is another way to access specific columns, using the <code>$</code> notation.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="structures.html#cb197-1"></a><span class="op">&gt;</span><span class="st"> </span>mtcars<span class="op">$</span>mpg</span></code></pre></div>
<pre><code>##  [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2
## [11] 17.8 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9
## [21] 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
## [31] 15.0 21.4</code></pre>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="structures.html#cb199-1"></a><span class="op">&gt;</span><span class="st"> </span>mtcars<span class="op">$</span>cyl</span></code></pre></div>
<pre><code>##  [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8
## [26] 4 4 4 8 6 8 4</code></pre>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="structures.html#cb201-1"></a><span class="op">&gt;</span><span class="st"> </span>mpg</span></code></pre></div>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mpg&#39; not found</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="structures.html#cb203-1"></a><span class="op">&gt;</span><span class="st"> </span>cyl</span></code></pre></div>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;cyl&#39; not found</code></pre>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="structures.html#cb205-1"></a><span class="op">&gt;</span><span class="st"> </span>weight</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<p>Notice that typing the variable name, such as <code>mpg</code>, without the name of the data frame (and a dollar sign) as a prefix, does not work. This is sensible. There may be several data frames that have variables named <code>mpg</code>, and just typing <code>mpg</code> doesn’t provide enough information to know which is desired. But if there is a vector named <code>mpg</code> that is created outside a data frame, it will be retrieved when <code>mpg</code> is typed, which is why typing <code>weight</code> does work, since <code>weight</code> was created outside of a data frame, although ultimately it was incorporated into the <code>healthData</code> data frame.</p>
</div>
</div>
<div id="lists" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Lists</h2>
<p>The third main data structure we will work with is a list. Technically a list is a vector, but one in which elements can be of different types. For example a list may have one element that is a vector, one element that is a data frame, and another element that is a function. Consider designing a function that fits a simple linear regression model to two quantitative variables. We might want that function to compute and return several things such as</p>
<ul>
<li>The fitted slope and intercept (a numeric vector with two components)</li>
<li>The residuals (a numeric vector with <span class="math inline">\(n\)</span> components, where <span class="math inline">\(n\)</span> is the number of data points)</li>
<li>Fitted values for the data (a numeric vector with <span class="math inline">\(n\)</span> components, where <span class="math inline">\(n\)</span> is the number of data points)</li>
<li>The names of the dependent and independent variables (a character vector with two components)</li>
</ul>
<p>In fact R has a function, <code>lm</code>, which does this (and much more).</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="structures.html#cb207-1"></a>mpgHpLinMod &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>hp, <span class="dt">data=</span>mtcars)</span>
<span id="cb207-2"><a href="structures.html#cb207-2"></a><span class="kw">mode</span>(mpgHpLinMod)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="structures.html#cb209-1"></a><span class="kw">names</span>(mpgHpLinMod)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;      
##  [4] &quot;rank&quot;          &quot;fitted.values&quot; &quot;assign&quot;       
##  [7] &quot;qr&quot;            &quot;df.residual&quot;   &quot;xlevels&quot;      
## [10] &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="structures.html#cb211-1"></a>mpgHpLinMod<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)          hp 
##    30.09886    -0.06823</code></pre>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="structures.html#cb213-1"></a>mpgHpLinMod<span class="op">$</span>residuals</span></code></pre></div>
<pre><code>##           Mazda RX4       Mazda RX4 Wag 
##            -1.59375            -1.59375 
##          Datsun 710      Hornet 4 Drive 
##            -0.95363            -1.19375 
##   Hornet Sportabout             Valiant 
##             0.54109            -4.83489 
##          Duster 360           Merc 240D 
##             0.91707            -1.46871 
##            Merc 230            Merc 280 
##            -0.81717            -2.50678 
##           Merc 280C          Merc 450SE 
##            -3.90678            -1.41777 
##          Merc 450SL         Merc 450SLC 
##            -0.51777            -2.61777 
##  Cadillac Fleetwood Lincoln Continental 
##            -5.71206            -5.02978 
##   Chrysler Imperial            Fiat 128 
##             0.29364             6.80421 
##         Honda Civic      Toyota Corolla 
##             3.84901             8.23598 
##       Toyota Corona    Dodge Challenger 
##            -1.98072            -4.36462 
##         AMC Javelin          Camaro Z28 
##            -4.66462            -0.08293 
##    Pontiac Firebird           Fiat X1-9 
##             1.04109             1.70421 
##       Porsche 914-2        Lotus Europa 
##             2.10991             8.01093 
##      Ford Pantera L        Ferrari Dino 
##             3.71340             1.54109 
##       Maserati Bora          Volvo 142E 
##             7.75761            -1.26198</code></pre>
<p>The <code>lm</code> function returns a list (which in the code above has been assigned to the object <code>mpgHpLinMod</code>).<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a> One component of the list is the length 2 vector of coefficients, while another component is the length 32 vector of residuals. The code also illustrates that named components of a list can be accessed using the dollar sign notation, as with data frames.</p>
<p>The <code>list</code> function is used to create lists.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="structures.html#cb215-1"></a>temporaryList &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">first=</span>weight, <span class="dt">second=</span>healthData,</span>
<span id="cb215-2"><a href="structures.html#cb215-2"></a>                      <span class="dt">pickle=</span><span class="kw">list</span>(<span class="dt">a =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dt">b=</span>healthData))</span>
<span id="cb215-3"><a href="structures.html#cb215-3"></a>temporaryList</span></code></pre></div>
<pre><code>## $first
## [1] 123 157 202 199 223 140 105 194
## 
## $second
##   Weight Gender bp.meds
## 1    123 female    TRUE
## 2    157 female    TRUE
## 3    202   male   FALSE
## 4    199 female    TRUE
## 5    223   male   FALSE
## 6    140   male   FALSE
## 7    105 female    TRUE
## 8    194   male    TRUE
## 
## $pickle
## $pickle$a
##  [1]  1  2  3  4  5  6  7  8  9 10
## 
## $pickle$b
##   Weight Gender bp.meds
## 1    123 female    TRUE
## 2    157 female    TRUE
## 3    202   male   FALSE
## 4    199 female    TRUE
## 5    223   male   FALSE
## 6    140   male   FALSE
## 7    105 female    TRUE
## 8    194   male    TRUE</code></pre>
<p>Here, for illustration, I assembled a list to hold some of the R data structures we have been working with in this chapter. The first list element, named <code>first</code>, holds the <code>weight</code> vector we created in Section <a href="structures.html#vector">4.1</a>, the second list element, named <code>second</code>, holds the <code>healthData</code> data frame, and the third list element, named <code>pickle</code>, holds a list with elements named <code>a</code> and <code>b</code> that hold a vector of values 1 through 10 and another copy of the <code>healthData</code> data frame, respectively. As this example shows, a list can contain another list.</p>
<div id="accessing-specific-elements-of-lists" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Accessing Specific Elements of Lists</h3>
<p>We already have seen the dollar sign notation works for lists. In addition, the square bracket subsetting notation can be used. There is an added, somewhat subtle wrinkle—using either single or double square brackets.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="structures.html#cb217-1"></a>temporaryList<span class="op">$</span>first</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="structures.html#cb219-1"></a><span class="kw">mode</span>(temporaryList<span class="op">$</span>first)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="structures.html#cb221-1"></a>temporaryList[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="structures.html#cb223-1"></a><span class="kw">mode</span>(temporaryList[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="structures.html#cb225-1"></a>temporaryList[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## $first
## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="structures.html#cb227-1"></a><span class="kw">mode</span>(temporaryList[<span class="dv">1</span>])</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>Note the dollar sign and double bracket notation return a numeric vector, while the single bracket notation returns a list. Notice also the difference in results below.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="structures.html#cb229-1"></a>temporaryList[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span></code></pre></div>
<pre><code>## $first
## [1] 123 157 202 199 223 140 105 194
## 
## $second
##   Weight Gender bp.meds
## 1    123 female    TRUE
## 2    157 female    TRUE
## 3    202   male   FALSE
## 4    199 female    TRUE
## 5    223   male   FALSE
## 6    140   male   FALSE
## 7    105 female    TRUE
## 8    194   male    TRUE</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="structures.html#cb231-1"></a>temporaryList[[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]]</span></code></pre></div>
<pre><code>## [1] 157</code></pre>
<p>The single bracket form returns the first and second elements of the list, while the double bracket form returns the second element in the first element of the list. Generally, do not put a vector of indices or names in a double bracket, you will likely get unexpected results. See, for example, the results below.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a></p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="structures.html#cb233-1"></a>temporaryList[[<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)]]</span></code></pre></div>
<pre><code>## Error in temporaryList[[c(1, 2, 3)]]: recursive indexing failed at level 2</code></pre>
<p>So, in summary, there are two main differences between using the single bracket <code>[]</code> and double bracket <code>[[]]</code>. First, the single bracket will return a list that holds the object(s) held at the given indices or names placed in the bracket, whereas the double brackets will return the actual object held at the index or name placed in the innermost bracket. Put differently, a single bracket can be used to access a range of list elements and will return a list, and a double bracket can only access a single element in the list and will return the object held at the index.</p>
</div>
</div>
<div id="logicalOperators" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Comparison and logical operators</h2>
<p><em>Comparison operators</em> are binary operators that test a comparative condition between the operands and return a logical value to indicate the test result. We often use comparison operators to gain access to only part of an R object that passes some logical test. You’re likely already familiar with many comparison operators.</p>
<p>The basic idea of comparison operators is quite simple. We have a logical test (e.g., what weights are greater than 200) and want to determine what values in a vector (or some other R object) pass the test. When we apply a comparison operator, the results are logical values that indicate whether or not the specific element in the vector passes the test (<code>TRUE</code>) or not (<code>FALSE</code>).</p>
<p>Let’s walk through the comparison operators available in R. We’ll present the operator and its definition, followed by an example using the <code>weight</code> and <code>gender</code> vectors created in Section <a href="structures.html#vector">4.1</a>. First, let’s recall the values held in these vectors.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="structures.html#cb235-1"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="structures.html#cb237-1"></a>gender</span></code></pre></div>
<pre><code>## [1] &quot;female&quot; &quot;female&quot; &quot;male&quot;   &quot;female&quot; &quot;male&quot;  
## [6] &quot;male&quot;   &quot;female&quot; &quot;male&quot;</code></pre>
<ol style="list-style-type: decimal">
<li><code>==</code> the equality operator: The “double equals sign” tests if operands are equal. Below we perform a logical test to determine which <code>gender</code> vector elements equal <code>male</code>.</li>
</ol>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="structures.html#cb239-1"></a>gender <span class="op">==</span><span class="st"> &quot;male&quot;</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE</code></pre>
<p>Not surprisingly, the third, fifth, sixth, and eigth elements return <code>TRUE</code> and all other elements return <code>FALSE</code>. Notice we’re using the <code>==</code> sign, not the <code>=</code> sign. Mixing up the comparison operator <code>==</code> and assignment operator <code>=</code> is a common error.</p>
<ol start="2" style="list-style-type: decimal">
<li><code>!=</code> the inequality operator: Tests if operands are not equal, and is thus the inverse of <code>==</code>. We see this by testing which <code>gender</code> vector elements do not equal <code>male</code>.</li>
</ol>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="structures.html#cb241-1"></a>gender <span class="op">!=</span><span class="st"> &quot;male&quot;</span></span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code> less than, less than or equal to, greater than, and greater than or equal to operators, respectively. Using the <code>weights</code> vector, determine which elements are greater than 194 and then greater than or equal to 194.</li>
</ol>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="structures.html#cb243-1"></a>weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">194</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="structures.html#cb245-1"></a>weight <span class="op">&gt;=</span><span class="st"> </span><span class="dv">194</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE</code></pre>
<p>Suppose we want to know which <code>weight</code> vector elements are greater than 194 <em>and</em> less than 210. Answering this question requires use of two comparison operators, i.e., <span class="math inline">\(&lt;\)</span> and <span class="math inline">\(&gt;\)</span>. In such cases, logical operators are used to combine multiple comparison operations into a single logical statement. We consider the following <em>logical operators</em> “and”, “or”, “xor”, and “negation”.</p>
<p>Importantly, in order of operation, comparison operators precede logical operators. The <code>Syntax</code> manual page (i.e., run <code>?Syntax</code> on the Console) lists R operators’ order of operation, where you’ll notice the comparison operators are listed before the logical operators in the precedence groups under the Details Section.</p>
<p>Let’s walk through each of the logical operators:</p>
<ol style="list-style-type: decimal">
<li><code>&amp;</code> the “and” operator: A comparison using the <code>&amp;</code> operator returns <code>TRUE</code> when both operands are <code>TRUE</code> and <code>FALSE</code> otherwise. The <code>&amp;</code> operator works elementwise for operand vectors. Consider the following example.</li>
</ol>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="structures.html#cb247-1"></a>weight <span class="op">&lt;</span><span class="st"> </span><span class="dv">210</span></span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="structures.html#cb249-1"></a>weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">194</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="structures.html#cb251-1"></a>weight <span class="op">&lt;</span><span class="st"> </span><span class="dv">210</span> <span class="op">&amp;</span><span class="st"> </span>weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">194</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE</code></pre>
<p>First we show the results of <code>weight &lt; 210</code> and <code>weight &gt; 194</code> separately. When combining the comparison operations using the <code>&amp;</code> operator, R first performs <code>weight &lt; 210</code> and <code>weight &gt; 194</code>, then applies <code>&amp;</code> elementwise on the logical vector operands. The elementwise <code>&amp;</code> returns <code>TRUE</code> when the element in the <code>weight &lt; 210</code> vector is <code>TRUE</code> and the element in the <code>weight &gt; 194</code> vector is <code>TRUE</code>. The key point to remember is that <code>&amp;</code> returns <code>TRUE</code> only if both operands are <code>TURE</code>.</p>
<ol start="2" style="list-style-type: decimal">
<li><code>|</code> the “or” operator: A comparison using the <code>|</code> operator returns <code>TRUE</code> if at least one operand is <code>TRUE</code> and <code>FALSE</code> otherwise. Similar to the <code>&amp;</code> operator, the <code>|</code> operator works element by element. Let’s use the same example as before, but now we’ll return individuals with a weight less than 210 or a weight greater than 194.</li>
</ol>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="structures.html#cb253-1"></a>weight <span class="op">&lt;</span><span class="st"> </span><span class="dv">210</span> <span class="op">|</span><span class="st"> </span>weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">194</span></span></code></pre></div>
<pre><code>## [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
<p>Not surprisingly, this operation returns <code>TRUE</code> for all elements, because all elements in <code>weight</code> are either greater than 194 or less than 210.</p>
<ol start="3" style="list-style-type: decimal">
<li><code>xor</code> the “exclusive or” operator: A comparison using the <code>xor</code> operator returns <code>TRUE</code> if one of the operands is <code>TRUE</code> and <code>FALSE</code> otherwise.</li>
</ol>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="structures.html#cb255-1"></a><span class="kw">xor</span>(weight <span class="op">&lt;</span><span class="st"> </span><span class="dv">210</span>, weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">194</span>)</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE</code></pre>
<p>While we can imagine cases where this operator would be handy, we’ve never found the occasion to use it in our own code.</p>
<ol start="4" style="list-style-type: decimal">
<li><code>!</code> the “negation” or “not” operator: The exclamation point <code>!</code> (called “bang” in programmer’s slang) reverses a logical value, i.e. <code>!TRUE</code> is <code>FALSE</code> and <code>!FALSE</code> is <code>TRUE</code>. The code below returns <code>TRUE</code> for weight values not greater than 194 (while not required, the parentheses emphasize the order of operation).</li>
</ol>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="structures.html#cb257-1"></a><span class="op">!</span>(weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">194</span>)</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE</code></pre>
<p>There is a “&amp;&amp;” and “||” variant of “&amp;” and “|”, respectively. These “double” operators examine only the first element of operand vectors in a comparison rather than comparing element by element. There are a few cases where using <code>&amp;&amp;</code> and <code>||</code> are useful when writing conditional statements in functions (see, e.g., Chapter <a href="functions.html#functions">7</a>), however, we’ll generally not use them in this book.</p>
<div id="inOperator" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> The <code>%in%</code> operator</h3>
<p>Suppose we want to identify the <code>weight</code> vector elements equal to 123, 199, or 140. We can do this using the equality operator <code>==</code> and the <code>|</code> operator as follows.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="structures.html#cb259-1"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="structures.html#cb261-1"></a>weight <span class="op">==</span><span class="st"> </span><span class="dv">123</span> <span class="op">|</span><span class="st"> </span>weight <span class="op">==</span><span class="st"> </span><span class="dv">199</span> <span class="op">|</span><span class="st"> </span>weight <span class="op">==</span><span class="st"> </span><span class="dv">140</span></span></code></pre></div>
<pre><code>## [1]  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
<p>However, this is a little clunky, involves a lot of typing, and generally makes code hard to read. Lucky for us, R has the “in” operator, <code>%in%</code>, to accomplish this task in a more intuitive and easy-to-read manner.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="structures.html#cb263-1"></a>weight <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">123</span>, <span class="dv">199</span>, <span class="dv">140</span>)</span></code></pre></div>
<pre><code>## [1]  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
<p>In the spirit of coding techniques to promote efficient and reproducible code, we’ll use the <code>%in%</code> operator throughout the book.</p>
<p>Comparison and logical operators are invaluable to identify subsets of data that meet specified conditions. The next section explores how conditional and logical operators facilitate subsetting vectors, data frames, and lists.</p>
</div>
</div>
<div id="subsetting" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Subsetting with Logical Vectors</h2>
<p>Consider the <code>healthData</code> data frame. How can we access only those weights which are more than 200? How can we access the genders of those whose weights are more than 200? How can we compute the mean weight of males and the mean weight of females? Or consider the <code>mtcars</code> data frame. How can we obtain the miles per gallon for all six cylinder cars? Both of these data sets are small enough that it would not be too onerous to extract the values by hand. But for larger or more complex data sets, this would be very difficult or impossible to do in a reasonable amount of time, and would likely result in errors.</p>
<p>R has a powerful method for solving these sorts of problems using a variant of the subsetting methods that we already have learned. When given a logical vector in square brackets, R will return the values corresponding to <code>TRUE</code>.
To begin, focus on the <code>weight</code> and <code>gender</code> vectors created in Section <a href="structures.html#vector">4.1</a>.</p>
<p>The R code <code>weight &gt; 200</code> returns a <code>TRUE</code> for each value of <code>weight</code> which is more than 200, and a <code>FALSE</code> for each value of <code>weight</code> which is less than or equal to 200. Similarly <code>gender == "female"</code> returns <code>TRUE</code> or <code>FALSE</code> depending on whether an element of <code>gender</code> is equal to <code>female</code>.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="structures.html#cb265-1"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="structures.html#cb267-1"></a>weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">200</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="structures.html#cb269-1"></a>gender[weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">200</span>]</span></code></pre></div>
<pre><code>## [1] &quot;male&quot; &quot;male&quot;</code></pre>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="structures.html#cb271-1"></a>weight[weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">200</span>]</span></code></pre></div>
<pre><code>## [1] 202 223</code></pre>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="structures.html#cb273-1"></a>gender <span class="op">==</span><span class="st"> &quot;female&quot;</span></span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="structures.html#cb275-1"></a>weight[gender <span class="op">==</span><span class="st"> &quot;female&quot;</span>]</span></code></pre></div>
<pre><code>## [1] 123 157 199 105</code></pre>
<p>Consider the lines of R code one by one.</p>
<ul>
<li><code>weight</code> instructs R to display the values in the vector <code>weight</code>.</li>
<li><code>weight &gt; 200</code> instructs R to check whether each value in <code>weight</code> is greater than 200, and to return <code>TRUE</code> if so, and <code>FALSE</code> otherwise.</li>
<li>The next line, <code>gender[weight &gt; 200]</code>, does two things. First, inside the square brackets, it does the same thing as the second line, namely, returning <code>TRUE</code> or <code>FALSE</code> depending on whether a value of <code>weight</code> is or is not greater than 200. Second, each element of <code>gender</code> is matched with the corresponding <code>TRUE</code> or <code>FALSE</code> value, and is returned if and only if the corresponding value is <code>TRUE</code>. For example the first value of <code>gender</code> is <code>gender[1]</code>. Since the first <code>TRUE</code> or <code>FALSE</code> value is <code>FALSE</code>, the first value of <code>gender</code> is not returned. Only the third and fifth values of <code>gender</code>, both of which happen to be <code>male</code>, are returned. Briefly, this line returns the genders of those people whose weight is over 200 pounds.</li>
<li>The fourth line of code, <code>weight[weight &gt; 200]</code>, again begins by returning <code>TRUE</code> or <code>FALSE</code> depending on whether elements of <code>weight</code> are larger than 200. Then those elements of <code>weight</code> corresponding to <code>TRUE</code> values, are returned. So this line returns the weights of those people whose weights are more than 200 pounds.</li>
<li>The fifth line returns <code>TRUE</code> or <code>FALSE</code> depending on whether elements of <code>gender</code> are equal to <code>female</code> or not.</li>
<li>The sixth line returns the weights of those whose gender is <code>female</code>.</li>
</ul>
<div id="modifying-or-creating-objects-via-subsetting" class="section level3" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Modifying or Creating Objects via Subsetting</h3>
<p>The results of subsetting can be assigned to a new (or existing) R object, and subsetting on the left side of an assignment is a common way to modify an existing R object.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="structures.html#cb277-1"></a>weight</span></code></pre></div>
<pre><code>## [1] 123 157 202 199 223 140 105 194</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="structures.html#cb279-1"></a>light.weight &lt;-<span class="st"> </span>weight[weight <span class="op">&lt;</span><span class="st"> </span><span class="dv">200</span>]</span>
<span id="cb279-2"><a href="structures.html#cb279-2"></a>light.weight</span></code></pre></div>
<pre><code>## [1] 123 157 199 140 105 194</code></pre>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="structures.html#cb281-1"></a>x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span></span>
<span id="cb281-2"><a href="structures.html#cb281-2"></a>x</span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="structures.html#cb283-1"></a>x[x <span class="op">&lt;</span><span class="st"> </span><span class="dv">5</span>] &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb283-2"><a href="structures.html#cb283-2"></a>x</span></code></pre></div>
<pre><code>##  [1]  0  0  0  0  5  6  7  8  9 10</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="structures.html#cb285-1"></a>y &lt;-<span class="st"> </span><span class="dv">-3</span><span class="op">:</span><span class="dv">9</span></span>
<span id="cb285-2"><a href="structures.html#cb285-2"></a>y</span></code></pre></div>
<pre><code>##  [1] -3 -2 -1  0  1  2  3  4  5  6  7  8  9</code></pre>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="structures.html#cb287-1"></a>y[y <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb287-2"><a href="structures.html#cb287-2"></a>y</span></code></pre></div>
<pre><code>##  [1] NA NA NA  0  1  2  3  4  5  6  7  8  9</code></pre>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="structures.html#cb289-1"></a><span class="kw">rm</span>(x)</span>
<span id="cb289-2"><a href="structures.html#cb289-2"></a><span class="kw">rm</span>(y)</span></code></pre></div>
</div>
<div id="logical-subsetting-and-data-frames" class="section level3" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> Logical Subsetting and Data Frames</h3>
<p>First consider the small and simple <code>healthData</code> data frame.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="structures.html#cb290-1"></a>healthData</span></code></pre></div>
<pre><code>##   Weight Gender bp.meds
## 1    123 female    TRUE
## 2    157 female    TRUE
## 3    202   male   FALSE
## 4    199 female    TRUE
## 5    223   male   FALSE
## 6    140   male   FALSE
## 7    105 female    TRUE
## 8    194   male    TRUE</code></pre>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="structures.html#cb292-1"></a>healthData<span class="op">$</span>Weight[healthData<span class="op">$</span>Gender <span class="op">==</span><span class="st"> &quot;male&quot;</span>]</span></code></pre></div>
<pre><code>## [1] 202 223 140 194</code></pre>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="structures.html#cb294-1"></a>healthData[healthData<span class="op">$</span>Gender <span class="op">==</span><span class="st"> &quot;female&quot;</span>, ]</span></code></pre></div>
<pre><code>##   Weight Gender bp.meds
## 1    123 female    TRUE
## 2    157 female    TRUE
## 4    199 female    TRUE
## 7    105 female    TRUE</code></pre>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="structures.html#cb296-1"></a>healthData[healthData<span class="op">$</span>Weight <span class="op">&gt;</span><span class="st"> </span><span class="dv">190</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>##   Gender bp.meds
## 3   male   FALSE
## 4 female    TRUE
## 5   male   FALSE
## 8   male    TRUE</code></pre>
<p>The first example is really just subsetting a vector, since the <code>$</code> notation creates vectors. The second two examples return subsets of the whole data frame. Note that the logical vector subsets the rows of the data frame, choosing those rows where the gender is female or the weight is more than 190. Note also that the specification for the columns (after the comma) is left blank in the first case, telling R to return all the columns. In the second case the second and third columns are requested explicitly.</p>
<p>Next consider the much larger and more complex <code>WorldBank</code> data frame. Recall, the <code>str</code> function displays the “structure” of an R object. Here is a look at the structure of several R objects.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="structures.html#cb298-1"></a><span class="kw">str</span>(mtcars)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="structures.html#cb300-1"></a><span class="kw">str</span>(temporaryList)</span></code></pre></div>
<pre><code>## List of 3
##  $ first : num [1:8] 123 157 202 199 223 140 105 194
##  $ second:&#39;data.frame&#39;:  8 obs. of  3 variables:
##   ..$ Weight : num [1:8] 123 157 202 199 223 140 105 194
##   ..$ Gender : chr [1:8] &quot;female&quot; &quot;female&quot; &quot;male&quot; &quot;female&quot; ...
##   ..$ bp.meds: logi [1:8] TRUE TRUE FALSE TRUE FALSE FALSE ...
##  $ pickle:List of 2
##   ..$ a: int [1:10] 1 2 3 4 5 6 7 8 9 10
##   ..$ b:&#39;data.frame&#39;:    8 obs. of  3 variables:
##   .. ..$ Weight : num [1:8] 123 157 202 199 223 140 105 194
##   .. ..$ Gender : chr [1:8] &quot;female&quot; &quot;female&quot; &quot;male&quot; &quot;female&quot; ...
##   .. ..$ bp.meds: logi [1:8] TRUE TRUE FALSE TRUE FALSE FALSE ...</code></pre>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="structures.html#cb302-1"></a><span class="kw">str</span>(WorldBank)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    11880 obs. of  15 variables:
##  $ iso2c                       : chr  &quot;AD&quot; &quot;AD&quot; &quot;AD&quot; &quot;AD&quot; ...
##  $ country                     : chr  &quot;Andorra&quot; &quot;Andorra&quot; &quot;Andorra&quot; &quot;Andorra&quot; ...
##  $ year                        : int  1978 1979 1977 2007 1976 2011 2012 2008 1980 1972 ...
##  $ fertility.rate              : num  NA NA NA 1.18 NA NA NA 1.25 NA NA ...
##  $ life.expectancy             : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ population                  : num  33746 34819 32769 81292 31781 ...
##  $ GDP.per.capita.Current.USD  : num  9128 11820 7751 39923 7152 ...
##  $ X15.to.25.yr.female.literacy: num  NA NA NA NA NA NA NA NA NA NA ...
##  $ iso3c                       : chr  &quot;AND&quot; &quot;AND&quot; &quot;AND&quot; &quot;AND&quot; ...
##  $ region                      : chr  &quot;Europe &amp; Central Asia (all income levels)&quot; &quot;Europe &amp; Central Asia (all income levels)&quot; &quot;Europe &amp; Central Asia (all income levels)&quot; &quot;Europe &amp; Central Asia (all income levels)&quot; ...
##  $ capital                     : chr  &quot;Andorra la Vella&quot; &quot;Andorra la Vella&quot; &quot;Andorra la Vella&quot; &quot;Andorra la Vella&quot; ...
##  $ longitude                   : num  1.52 1.52 1.52 1.52 1.52 ...
##  $ latitude                    : num  42.5 42.5 42.5 42.5 42.5 ...
##  $ income                      : chr  &quot;High income: nonOECD&quot; &quot;High income: nonOECD&quot; &quot;High income: nonOECD&quot; &quot;High income: nonOECD&quot; ...
##  $ lending                     : chr  &quot;Not classified&quot; &quot;Not classified&quot; &quot;Not classified&quot; &quot;Not classified&quot; ...</code></pre>
<p>First we see that <code>mtcars</code> is a data frame which has 32 observations (rows) on each of 11 variables (columns). The names of the variables are given, along with their type (in this case, all numeric), and the first few values of each variable is given.</p>
<p>Second we see that <code>temporaryList</code> is a list with three components. Each of the components is described separately, with the first few values again given.</p>
<p>Third we examine the structure of <code>WorldBank</code>. It is a data frame with 11880 observations on each of 15 variables. Some of these are character variables, some are numeric, and one (<code>year</code>) is integer. Looking at the first few values we see that some variables have missing values.</p>
<p>Consider creating a data frame which only has the observations from one year, say 1971. That’s relatively easy. Just choose rows for which <code>year</code> is equal to 1971.</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="structures.html#cb304-1"></a>WorldBank1971 &lt;-<span class="st"> </span>WorldBank[WorldBank<span class="op">$</span>year <span class="op">==</span><span class="st"> </span><span class="dv">1971</span>, ]</span>
<span id="cb304-2"><a href="structures.html#cb304-2"></a><span class="kw">dim</span>(WorldBank1971)</span></code></pre></div>
<pre><code>## [1] 216  15</code></pre>
<p>The <code>dim</code> function returns the dimensions of a data frame, i.e., the number of rows and the number of columns. From <code>dim</code> we see that there are <code>dim(WorldBank1971)[1]</code> cases from 1971.</p>
<p>Next, how can we create a data frame which only contains data from 1971, and also only contains cases for which there are no missing values in the fertility rate variable? R has a built in function <code>is.na</code> which returns <code>TRUE</code> if the observation is missing and returns <code>FALSE</code> otherwise. And <code>!is.na</code> returns the negation, i.e., it returns <code>FALSE</code> if the observation is missing and <code>TRUE</code> if the observation is not missing.</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="structures.html#cb306-1"></a>WorldBank1971<span class="op">$</span>fertility.rate[<span class="dv">1</span><span class="op">:</span><span class="dv">25</span>]</span></code></pre></div>
<pre><code>##  [1]    NA 6.512 7.671 3.517 4.933 3.118 7.264 3.104
##  [9]    NA 2.200 2.961 2.788 4.479 2.260 2.775 2.949
## [17] 6.942 2.210 6.657 2.100 6.293 7.329 6.786    NA
## [25] 5.771</code></pre>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="structures.html#cb308-1"></a><span class="op">!</span><span class="kw">is.na</span>(WorldBank1971<span class="op">$</span>fertility.rate[<span class="dv">1</span><span class="op">:</span><span class="dv">25</span>])</span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [9] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [17]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
## [25]  TRUE</code></pre>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="structures.html#cb310-1"></a>WorldBank1971 &lt;-<span class="st"> </span>WorldBank1971[<span class="op">!</span><span class="kw">is.na</span>(WorldBank1971<span class="op">$</span>fertility.rate),]</span>
<span id="cb310-2"><a href="structures.html#cb310-2"></a><span class="kw">dim</span>(WorldBank1971)</span></code></pre></div>
<pre><code>## [1] 193  15</code></pre>
<p>From <code>dim</code> we see that there are 193 cases from 1971 with non-missing fertility rate data.</p>
<p>Return attention now to the original <code>WorldBank</code> data frame with data not only from 1971. How can we extract only those cases (rows) which have NO missing data? Consider the following simple example:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="structures.html#cb312-1"></a>temporaryDataFrame &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">V1 =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="ot">NA</span>),</span>
<span id="cb312-2"><a href="structures.html#cb312-2"></a>                                 <span class="dt">V2 =</span> <span class="kw">c</span>(<span class="ot">NA</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="ot">NA</span>),</span>
<span id="cb312-3"><a href="structures.html#cb312-3"></a>                                 <span class="dt">V3 =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>))</span>
<span id="cb312-4"><a href="structures.html#cb312-4"></a>temporaryDataFrame</span></code></pre></div>
<pre><code>##   V1 V2 V3
## 1  1 NA  1
## 2  2  1  2
## 3  3  4  3
## 4  4  5  5
## 5 NA NA  7</code></pre>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="structures.html#cb314-1"></a><span class="kw">is.na</span>(temporaryDataFrame)</span></code></pre></div>
<pre><code>##         V1    V2    V3
## [1,] FALSE  TRUE FALSE
## [2,] FALSE FALSE FALSE
## [3,] FALSE FALSE FALSE
## [4,] FALSE FALSE FALSE
## [5,]  TRUE  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="structures.html#cb316-1"></a><span class="kw">rowSums</span>(<span class="kw">is.na</span>(temporaryDataFrame))</span></code></pre></div>
<pre><code>## [1] 1 0 0 0 2</code></pre>
<p>First notice that <code>is.na</code> will test each element of a data frame for missingness. Also recall that if R is asked to sum a logical vector, it will first convert the logical vector to numeric and then compute the sum, which effectively counts the number of elements in the logical vector which are <code>TRUE</code>. The <code>rowSums</code> function computes the sum of each row. So <code>rowSums(is.na(temporaryDataFrame))</code> returns a vector with as many elements as there are rows in the data frame. If an element is zero, the corresponding row has no missing values. If an element is greater than zero, the value is the number of variables which are missing in that row. This gives a simple method to return all the cases which have no missing data.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="structures.html#cb318-1"></a><span class="kw">dim</span>(WorldBank)</span></code></pre></div>
<pre><code>## [1] 11880    15</code></pre>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="structures.html#cb320-1"></a>WorldBankComplete &lt;-<span class="st"> </span>WorldBank[<span class="kw">rowSums</span>(<span class="kw">is.na</span>(WorldBank)) <span class="op">==</span><span class="st"> </span><span class="dv">0</span>,]</span>
<span id="cb320-2"><a href="structures.html#cb320-2"></a><span class="kw">dim</span>(WorldBankComplete)</span></code></pre></div>
<pre><code>## [1] 564  15</code></pre>
<p>Out of the 564 rows in the original data frame, only 564 have no missing observations!</p>
</div>
</div>
<div id="patterned-data" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Patterned Data</h2>
<p>Sometimes it is useful to generate all the integers from 1 through 20, to generate a sequence of 100 points equally spaced between 0 and 1, etc. The R functions <code>seq()</code> and <code>rep()</code> as well as the “colon operator” <code>:</code> help to generate such sequences.</p>
<p>The colon operator generates a sequence of values with increments of <span class="math inline">\(1\)</span> or <span class="math inline">\(-1\)</span>.</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="structures.html#cb322-1"></a><span class="dv">1</span><span class="op">:</span><span class="dv">10</span></span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="structures.html#cb324-1"></a><span class="dv">-5</span><span class="op">:</span><span class="dv">3</span></span></code></pre></div>
<pre><code>## [1] -5 -4 -3 -2 -1  0  1  2  3</code></pre>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="structures.html#cb326-1"></a><span class="dv">10</span><span class="op">:</span><span class="dv">4</span></span></code></pre></div>
<pre><code>## [1] 10  9  8  7  6  5  4</code></pre>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="structures.html#cb328-1"></a>pi<span class="op">:</span><span class="dv">7</span></span></code></pre></div>
<pre><code>## [1] 3.142 4.142 5.142 6.142</code></pre>
<p>The <code>seq()</code> function generates either a sequence of pre-specified length or a sequence with pre-specified increments.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="structures.html#cb330-1"></a><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">length =</span> <span class="dv">11</span>)</span></code></pre></div>
<pre><code>##  [1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0</code></pre>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="structures.html#cb332-1"></a><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">1</span>, <span class="dt">to =</span> <span class="dv">5</span>, <span class="dt">by =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>##  [1] 1.000 1.333 1.667 2.000 2.333 2.667 3.000 3.333
##  [9] 3.667 4.000 4.333 4.667 5.000</code></pre>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="structures.html#cb334-1"></a><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">3</span>, <span class="dt">to =</span> <span class="dv">-1</span>, <span class="dt">length =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1]  3.0000  2.5556  2.1111  1.6667  1.2222  0.7778
##  [7]  0.3333 -0.1111 -0.5556 -1.0000</code></pre>
<p>The <code>rep()</code> function replicates the values in a given vector.</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="structures.html#cb336-1"></a><span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>), <span class="dt">length =</span> <span class="dv">9</span>)</span></code></pre></div>
<pre><code>## [1] 1 2 4 1 2 4 1 2 4</code></pre>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="structures.html#cb338-1"></a><span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>), <span class="dt">times =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 1 2 4 1 2 4 1 2 4</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="structures.html#cb340-1"></a><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;c&quot;</span>), <span class="dt">times =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>))</span></code></pre></div>
<pre><code>##  [1] &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;b&quot; &quot;b&quot; &quot;c&quot; &quot;c&quot; &quot;c&quot; &quot;c&quot; &quot;c&quot; &quot;c&quot; &quot;c&quot;</code></pre>
<div id="ch4PP3" class="section level3" number="4.8.1">
<h3><span class="header-section-number">4.8.1</span> Practice Problem</h3>
<p>Often when using R you will want to simulate data from a specific probability distribution (i.e. normal/Gaussian, bionmial, Poisson). R has a vast suite of functions for working with statistical distributions. To generate values from a statistical distribution, the function has a name beginning with an “r” followed by some abbreviation of the probability distribution. For example to simulate from the three distributions mentioned above, we can use the functions <code>rnorm()</code>, <code>rbinom()</code>, and <code>rpois()</code>.</p>
<p>Use the <code>rnorm()</code> function to generate 10,000 values from the standard normal distribution (the normal distribution with mean = 0 and variance = 1). Consult the help page for <code>rnorm()</code> if you need to. Save this vector of variables to a vector named <code>sim.vals</code>. Then use the <code>hist()</code> function to draw a histogram of the simulated data. Does the data look like it follows a normal distribution?</p>
</div>
</div>
<div id="exChapter4" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Exercises</h2>
<p><strong>Exercise 3</strong> Learning objectives: create, subset, and manipulate vector contents and attributes; summarize vector data using R <code>table()</code> and other functions; generate basic graphics using vector data.</p>
<p><strong>Exercise 4</strong> Learning objectives: use functions to describe data frame characteristics; summarize and generate basic graphics for variables held in data frames; apply the subset function with logical operators; illustrate <code>NA</code>, <code>NaN</code>, <code>Inf</code>, and other special values; recognize the implications of using floating point arithmetic with logical operators.</p>
<p><strong>Exercise 5</strong> Learning objectives: practice with lists, data frames, and associated functions; summarize variables held in lists and data frames; work with R’s linear regression <code>lm()</code> function output; review logical subsetting of vectors for partitioning and assigning of new values; generate and visualize data from mathematical functions.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="23">
<li id="fn23"><p>Technically the objects described in this section are “atomic” vectors (all elements of the same type), since lists, to be described below, also are actually vectors. This will not be an important issue, and the shorter term vector will be used for atomic vectors below.<a href="structures.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>Missing data will be discussed in more detail later in the chapter.<a href="structures.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>The <code>mode</code> function returns the type or storage mode of an object.<a href="structures.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>Try this example using only single brackets<span class="math inline">\(\ldots\)</span> it will return a list holding elements <code>first</code>, <code>second</code>, and <code>pickle</code>.<a href="structures.html#fnref26" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scripts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ggplot2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown/edit/master/inst/examples/04-dataStructures.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub", "bookdown.mobi"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
