---
authors:
- admin
categories: []
date: "2021-04-08T00:00:00Z"
draft: false
featured: false
lastmod: "2021-04-08T00:00:00Z"
projects: []
subtitle: 'Quick instructions for installing R and RStudio'
summary: Quick instructions for installing R and RStudio
tags:
- Academic
title: 'Installing R and RStudio'
---

## Obtaining and installing R

It's simple to install R on computers running Microsoft Windows, macOS, or Linux. For other operating systems, users can compile the source code directly.^[Windows, macOS, and Linux users also can compile the source code directly, but for most it's a better idea to install R from already compiled binary distributions.]
Following is a step-by-step guide to installing R for Microsoft Windows.^[New versions of R are released regularly, so the version number in Step 6 might be different from what is listed below.] macOS and Linux users would follow similar steps.

1. Go to http://www.r-project.org/
2. Click on the `CRAN` link on the left side of the page
3. Choose one of the mirrors^[As the name implies, all *mirrors* provide the exact same software. The https://cloud.r-project.org/ mirror is usually fast; otherwise choose a mirror close to your geographic location.]
4. Click on `Download R for Windows`
5. Click on `base`
6. Click on `Download R 4.0.2 for Windows`
7. Install R as you would install any other Windows program

## Obtaining and installing RStudio

You must install R prior to installing RStudio. RStudio is also simple to install:

1. Go to http://www.rstudio.com
2. Click on the link `RStudio` under the `Products` tab
3. Click on the `RStudio Desktop` box
4. Choose the `DOWNLOAD RSTUDIO DESKTOP` link in the `Open Source Edition` column
5. On the ensuing page, click on the `Installer` version for your operating system, and once downloaded, install as you would any other program
