---
title: "Temporal Autocorrelation Structures and Repeated Measures"
author: "Jeff Doser"
date: "April 7, 2020"
categories: ["R"]
tags: ["statistics", "experimental design", "time-series"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = NA)
```

In this document I provide some details to potentially help clarify the concept of "repeated measures". I have often found these sorts of experimental design terms to be very confusing. Here I hope to clarify the concept of repeated measures as a method to account for temporal autocorrelation in a dataset. 

Repeated measures designs are a specific type of design where there is some sort of temporal autocorrelation among data points. Specifically, in a repeated measures design it is assumed that the same individual study units (e.g., trees) are measured at multiple time points. Thus, from an experimental design standpoint, one can view individuals as being a blocking variable and the variation within the subject represents the experimental error. Thinking hierarchically, we can imagine our full set of data points in a regression where at the second level there is a random effect of "individual", where these are 0-centered normally distributed variables with a single variance, where that variance is said to account for the similarity among individuals. 

This sort of example I just discussed where the subjects that are repatedly measured over time are treated as a blocking variable (i.e., random effect) is the most basic sort of repeated measures design. In fact, this has a special name, and is referred to as **Compound Symmetry**. You can also view this as saying that "observations within a subject are equally correlated with each other". This most basic type of repeated measures design can be summed up in the following basic hierarchical model: 

$$
\begin{aligned}
y_{ij} \mid \omega_j &\sim \text{Normal}(\mu + \mu_i + \omega_j, \sigma^2) \\
\omega_j &\sim \text{Normal}(0, \tau^2)
\end{aligned}
$$

From this hierarchical model, it is clear how this most basic repeated measures design works (which is also equivalent to a basic RCBD with the blocking factor being random). It is also clear from this hierarchical perspective the variance components incorporated in the measurements for each individual measurement. 

**Key Point**: repeated measures designs are extensions of a basic random effects model that provides more structure of how data points within a blocking variable are related to each other. Repeated measures are simply a method to account for non-indenpendence of data points that specifically has to do with temporal autocorrelation.

Let's next consider some other basic autocorrelation structures.

### AR(1)

The AR(1) covariance structure is very commonly used in time-series applications. One important thing to consider is that the AR(1) requires equally spaced intervals of time. The covariance structure takes the following form: 


$$
\sigma^2
\begin{pmatrix}
1 & \rho & \rho^2 & \rho^3 & \dots \\
\rho & 1 & \rho & \rho^2 & \dots \\
\rho^2 & \rho & 1 & \rho & \dots \\
\rho^3 & \rho^2 & \rho & 1 & \dots
\end{pmatrix}
$$

Notice how this structure assumes constant variance among the observations. In an hierarchical model, one can consider the structure of the model to take the following form for any given set of values $\boldsymbol{y}$ that come from the same group that is repeatedly measured over time. 

$$
\begin{aligned}
\boldsymbol{y}_j \mid \boldsymbol{\omega}_j &\sim \text{Normal}(\mu + \boldsymbol{\mu}_j + \boldsymbol{\omega}_j, \text{diag}(\sigma^2)) \\
\boldsymbol{\omega}_j &\sim \text{Normal}(\boldsymbol{0}, \tau^2\boldsymbol{\Sigma}(\rho))
\end{aligned}
$$

where $\tau^2\boldsymbol{\Sigma}(\rho)$ is equivalent to the AR(1) covariance structure defined above. 

There are numerous other covariance structures that can be assumed depending on the structure one thinks can be reasonable for the data. 


## Double Repeated Measures

Now let's consider the situation where one expects temporal autocorrelation over two separate time periods. In other words, there are two units of time where repeated measures take place, and it is not reasonable to group these into a single time unit. 

This is actually exactly analogous to what you did in your first publication. This concept would be a double repeated measures where you have an unstructured covariance matrix for the time of day, and then an AR(1) covariance matrix for the 29 minute recordings. 