---
title: "Simple Linear Regression"
author: "Jeff Doser"
date: "April 10, 2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

The basic simple linear regression model is ubiquitous in ecology. The model takes the following form: 

$$
y = \beta_0 + \beta_1x + e \\
e \sim (0, \sigma^2)
$$

where $y$ is the dependent response variable and $x$ is the independent explanatory variable. The first step to do prior to performing a linear regression should be to plot $y$ versus $x$ to confirm a linear relationship between the variables exists. 

$\beta_0$ is the y-intercept and $\beta_1$ is the change in unit $y$ for a change in unit $x$. 

There are numerous ways to estimate the regression parameters $\beta_0$ and $\beta_1$, but of course the most common method to use is called **Least Squares Estimation**. Remember the crucial assumption of least squares estimation: 

$$
e_i \sim IID(0, \sigma^2)
$$

for all $i = 1, 2, \dots, n$. Note that for actually estimating the parameters $\beta_0$ and $\beta_1$ you do not need to assume normality of the errors, but if you wish to do any sort of hypothesis testing than you do need to. 

The idea behind least squares estimation is to minimize the sum of squares of the residuals: 

$$
\sum_{i = 1}^ne_i^2 = \sum_{i = 1}^n(y_i - \beta_0 - \beta_1x_i)^2
$$

